import React, { useState, useEffect } from "react";
import $ from "jquery";
import "../../Pages/ElectricBill/ElectricBill.scss";
import "./NewLocation.scss";
import { GrMapLocation } from "react-icons/gr";

function NewLocation() {
  const countries = [
    { serial: "1", id: "Abia" },
    { serial: "2", id: "Adamawa" },
    { serial: "3", id: "Akwa Ibom" },
    { serial: "4", id: "Anambra" },
    { serial: "5", id: "Bauchi" },
    { serial: "6", id: "Bayelsa" },
    { serial: "7", id: "Benue" },
    { serial: "8", id: "Borno" },
    { serial: "9", id: "Cross River" },
    { serial: "10", id: "Delta" },
    { serial: "11", id: "Ebonyi" },
    { serial: "12", id: "Edo" },
    { serial: "13", id: "Ekiti" },
    { serial: "14", id: "Enugu" },
    { serial: "15", id: "FCT - Abuja" },
    { serial: "16", id: "Gombe" },
    { serial: "17", id: "Imo" },
    { serial: "18", id: "Jigawa" },
    { serial: "19", id: "Kaduna" },
    { serial: "20", id: "Kano" },
    { serial: "21", id: "Katsina" },
    { serial: "22", id: "Kebbi" },
    { serial: "23", id: "Kogi" },
    { serial: "24", id: "Kwara" },
    { serial: "25", id: "Lagos" },
    { serial: "26", id: "Nasarawa" },
    { serial: "27", id: "Niger" },
    { serial: "28", id: "Ogun" },
    { serial: "29", id: "Ondo" },
    { serial: "30", id: "Osun" },
    { serial: "31", id: "Oyo" },
    { serial: "32", id: "Plateau" },
    { serial: "33", id: "Rivers" },
    { serial: "34", id: "Sokoto" },
    { serial: "35", id: "Taraba" },
    { serial: "36", id: "Yobe" },
    { serial: "37", id: "Zamfara" },
  ];

  const states = [
    { serial: "1", countryId: "Abia", id: "Aba North" },
    { serial: "2", countryId: "Abia", id: "Aba South" },
    { serial: "3", countryId: "Abia", id: "Arochukwu" },
    { serial: "4", countryId: "Abia", id: "Bende" },
    { serial: "5", countryId: "Abia", id: "Ikwuano" },
    { serial: "6", countryId: "Abia", id: "Isiala-Ngwa North" },
    { serial: "7", countryId: "Abia", id: "Isiala-Ngwa South" },
    { serial: "8", countryId: "Abia", id: "Isuikwuato" },
    { serial: "9", countryId: "Abia", id: "Obi Nwa" },
    { serial: "10", countryId: "Abia", id: "Ohafia" },
    { serial: "11", countryId: "Abia", id: "Osisioma" },
    { serial: "12", countryId: "Abia", id: "Ngwa" },
    { serial: "13", countryId: "Abia", id: "Ugwunagbo" },
    { serial: "14", countryId: "Abia", id: "Ukwa East" },
    { serial: "15", countryId: "Abia", id: "Ukwa West" },
    { serial: "16", countryId: "Abia", id: "Umuahia North" },
    { serial: "17", countryId: "Abia", id: "Umuahia South" },
    { serial: "18", countryId: "Abia", id: "Umu-Neochi" },
    { serial: "19", countryId: "Adamawa", id: "Demsa" },
    { serial: "20", countryId: "Adamawa", id: "Fufore" },
    { serial: "21", countryId: "Adamawa", id: "Ganye" },
    { serial: "22", countryId: "Adamawa", id: "Girei" },
    { serial: "23", countryId: "Adamawa", id: "Gombi" },
    { serial: "24", countryId: "Adamawa", id: "Guyuk" },
    { serial: "25", countryId: "Adamawa", id: "Hong" },
    { serial: "26", countryId: "Adamawa", id: "Jada" },
    { serial: "27", countryId: "Adamawa", id: "Lamurde" },
    { serial: "28", countryId: "Adamawa", id: "Madagali" },
    { serial: "29", countryId: "Adamawa", id: "Maiha" },
    { serial: "30", countryId: "Adamawa", id: "Mayo-Belwa" },
    { serial: "31", countryId: "Adamawa", id: "Michika" },
    { serial: "32", countryId: "Adamawa", id: "Mubi North" },
    { serial: "33", countryId: "Adamawa", id: "Mubi South" },
    { serial: "34", countryId: "Adamawa", id: "Numan" },
    { serial: "35", countryId: "Adamawa", id: "Shelleng" },
    { serial: "36", countryId: "Adamawa", id: "Song" },
    { serial: "37", countryId: "Adamawa", id: "Toungo" },
    { serial: "38", countryId: "Adamawa", id: "Yola North" },
    { serial: "39", countryId: "Adamawa", id: "Yola South" },
    { serial: "40", countryId: "Akwa Ibom", id: "Aguata" },
    { serial: "41", countryId: "Akwa Ibom", id: "Anambra East" },
    { serial: "42", countryId: "Akwa Ibom", id: "Anambra West" },
    { serial: "43", countryId: "Akwa Ibom", id: "Anaocha" },
    { serial: "44", countryId: "Akwa Ibom", id: "Akwa North" },
    { serial: "45", countryId: "Akwa Ibom", id: "Akwa South" },
    { serial: "46", countryId: "Akwa Ibom", id: "Ayamelum" },
    { serial: "47", countryId: "Akwa Ibom", id: "Dunukofia" },
    { serial: "48", countryId: "Akwa Ibom", id: "Ekwusigo" },
    { serial: "49", countryId: "Akwa Ibom", id: "Idemili North" },
    { serial: "50", countryId: "Akwa Ibom", id: "Idemili South" },
    { serial: "51", countryId: "Akwa Ibom", id: "Ihiala" },
    { serial: "52", countryId: "Akwa Ibom", id: "Njikoka" },
    { serial: "53", countryId: "Akwa Ibom", id: "Nnewi North" },
    { serial: "54", countryId: "Akwa Ibom", id: "Nnewi South" },
    { serial: "55", countryId: "Akwa Ibom", id: "Ogbaru" },
    { serial: "56", countryId: "Akwa Ibom", id: "Onitsha North" },
    { serial: "57", countryId: "Akwa Ibom", id: "Onitsha South" },
    { serial: "58", countryId: "Akwa Ibom", id: "Orumba North" },
    { serial: "59", countryId: "Akwa Ibom", id: "Orumba South" },
    { serial: "60", countryId: "Akwa Ibom", id: "Oyi" },
    { serial: "61", countryId: "Anambra", id: "Abak" },
    { serial: "62", countryId: "Anambra", id: "Eastern Obolo" },
    { serial: "63", countryId: "Anambra", id: "Eket" },
    { serial: "64", countryId: "Anambra", id: "Esit-Eket" },
    { serial: "65", countryId: "Anambra", id: "Essien Udim" },
    { serial: "66", countryId: "Anambra", id: "Etim-Ekpo" },
    { serial: "67", countryId: "Anambra", id: "Etinan" },
    { serial: "68", countryId: "Anambra", id: "Ibeno" },
    { serial: "69", countryId: "Anambra", id: "Ibesikpo-Asutan" },
    { serial: "70", countryId: "Anambra", id: "Ibiono-Ibom" },
    { serial: "71", countryId: "Anambra", id: "Ika" },
    { serial: "72", countryId: "Anambra", id: "Ikono" },
    { serial: "73", countryId: "Anambra", id: "Ikot Abasi" },
    { serial: "74", countryId: "Anambra", id: "Ikot Ekpene" },
    { serial: "75", countryId: "Anambra", id: "Ini" },
    { serial: "76", countryId: "Anambra", id: "Itu" },
    { serial: "77", countryId: "Anambra", id: "Mbo" },
    { serial: "78", countryId: "Anambra", id: "Mkpat-Enin" },
    { serial: "79", countryId: "Anambra", id: "Nsit-Atai" },
    { serial: "80", countryId: "Anambra", id: "Nsit-Ibom" },
    { serial: "81", countryId: "Anambra", id: "Nsit-Ubium" },
    { serial: "82", countryId: "Anambra", id: "Obot-Akara" },
    { serial: "83", countryId: "Anambra", id: "Okobo" },
    { serial: "84", countryId: "Anambra", id: "Onna" },
    { serial: "85", countryId: "Anambra", id: "Oron" },
    { serial: "86", countryId: "Anambra", id: "Oruk Anam" },
    { serial: "87", countryId: "Anambra", id: "Udung Uko" },
    { serial: "88", countryId: "Anambra", id: "Ukanafun" },
    { serial: "89", countryId: "Anambra", id: "Uruan" },
    { serial: "90", countryId: "Anambra", id: "Urue-Offong/Oruko" },
    { serial: "91", countryId: "Anambra", id: "Uyo" },
    { serial: "92", countryId: "Bauchi", id: "Alkaleri" },
    { serial: "93", countryId: "Bauchi", id: "Bauchi" },
    { serial: "94", countryId: "Bauchi", id: "Bauchi Town" },
    { serial: "95", countryId: "Bauchi", id: "Bogoro" },
    { serial: "96", countryId: "Bauchi", id: "Dambam" },
    { serial: "97", countryId: "Bauchi", id: "Darazo" },
    { serial: "98", countryId: "Bauchi", id: "Dass" },
    { serial: "99", countryId: "Bauchi", id: "Gamawa" },
    { serial: "100", countryId: "Bauchi", id: "Ganjuwa" },
    { serial: "101", countryId: "Bauchi", id: "Giade" },
    { serial: "102", countryId: "Bauchi", id: "Itas/Gadau" },
    { serial: "103", countryId: "Bauchi", id: "Jama'are" },
    { serial: "104", countryId: "Bauchi", id: "Katagum" },
    { serial: "105", countryId: "Bauchi", id: "Kirfi" },
    { serial: "106", countryId: "Bauchi", id: "Misau" },
    { serial: "107", countryId: "Bauchi", id: "Ningi" },
    { serial: "108", countryId: "Bauchi", id: "Shira" },
    { serial: "109", countryId: "Bauchi", id: "Tafawa-Balewa" },
    { serial: "110", countryId: "Bauchi", id: "Toro" },
    { serial: "111", countryId: "Bauchi", id: "Warji" },
    { serial: "112", countryId: "Bauchi", id: "Zaki" },
    { serial: "113", countryId: "Bayelsa", id: "Brass" },
    { serial: "114", countryId: "Bayelsa", id: "Ekeremor" },
    { serial: "115", countryId: "Bayelsa", id: "Kolokuma/Opokuma" },
    { serial: "116", countryId: "Bayelsa", id: "Nembe" },
    { serial: "117", countryId: "Bayelsa", id: "Ogbia" },
    { serial: "118", countryId: "Bayelsa", id: "Sagbama" },
    { serial: "119", countryId: "Bayelsa", id: "Southern Ijaw" },
    { serial: "120", countryId: "Bayelsa", id: "Yenagoa" },
    { serial: "121", countryId: "Benue", id: "Ado" },
    { serial: "122", countryId: "Benue", id: "Agatu" },
    { serial: "123", countryId: "Benue", id: "Apa" },
    { serial: "124", countryId: "Benue", id: "buruku" },
    { serial: "125", countryId: "Benue", id: "Gboko" },
    { serial: "126", countryId: "Benue", id: "Guma" },
    { serial: "127", countryId: "Benue", id: "Gwer East" },
    { serial: "128", countryId: "Benue", id: "Gwer West" },
    { serial: "129", countryId: "Benue", id: "Katsina-Ala" },
    { serial: "130", countryId: "Benue", id: "Konshisha" },
    { serial: "131", countryId: "Benue", id: "Kwande" },
    { serial: "132", countryId: "Benue", id: "Logo" },
    { serial: "133", countryId: "Benue", id: "Makurdi" },
    { serial: "134", countryId: "Benue", id: "Obi" },
    { serial: "135", countryId: "Benue", id: "Ogbadibo" },
    { serial: "136", countryId: "Benue", id: "Oju" },
    { serial: "137", countryId: "Benue", id: "Okpokwu" },
    { serial: "138", countryId: "Benue", id: "Ohimini" },
    { serial: "139", countryId: "Benue", id: "Oturkpo" },
    { serial: "140", countryId: "Benue", id: "Tarka" },
    { serial: "141", countryId: "Benue", id: "Ukum" },
    { serial: "142", countryId: "Benue", id: "Ushongo" },
    { serial: "143", countryId: "Benue", id: "Vandeikya" },
    { serial: "144", countryId: "Borno", id: "Abadam" },
    { serial: "145", countryId: "Borno", id: "Askira/Uba" },
    { serial: "146", countryId: "Borno", id: "Bama" },
    { serial: "147", countryId: "Borno", id: "Bayo" },
    { serial: "148", countryId: "Borno", id: "Biu" },
    { serial: "149", countryId: "Borno", id: "Chibok" },
    { serial: "150", countryId: "Borno", id: "Damboa" },
    { serial: "151", countryId: "Borno", id: "Dikwa" },
    { serial: "152", countryId: "Borno", id: "Gubio" },
    { serial: "153", countryId: "Borno", id: "Guzamala" },
    { serial: "154", countryId: "Borno", id: "Gwoza" },
    { serial: "155", countryId: "Borno", id: "Hawul" },
    { serial: "156", countryId: "Borno", id: "Jere" },
    { serial: "157", countryId: "Borno", id: "Kaga" },
    { serial: "158", countryId: "Borno", id: "Kala/Balge" },
    { serial: "159", countryId: "Borno", id: "Konduga" },
    { serial: "160", countryId: "Borno", id: "Kukawa" },
    { serial: "161", countryId: "Borno", id: "Kwaya Kusar" },
    { serial: "162", countryId: "Borno", id: "Mafa" },
    { serial: "163", countryId: "Borno", id: "Magumeri" },
    { serial: "164", countryId: "Borno", id: "Maiduguri" },
    { serial: "165", countryId: "Borno", id: "Marte" },
    { serial: "166", countryId: "Borno", id: "Mobbar" },
    { serial: "167", countryId: "Borno", id: "Monguno" },
    { serial: "168", countryId: "Borno", id: "Ngala" },
    { serial: "169", countryId: "Borno", id: "Nganzai" },
    { serial: "170", countryId: "Borno", id: "Shani" },
    { serial: "171", countryId: "Cross River", id: "Akpabuyo" },
    { serial: "172", countryId: "Cross River", id: "Odukpani" },
    { serial: "173", countryId: "Cross River", id: "Akamkpa" },
    { serial: "174", countryId: "Cross River", id: "Biase" },
    { serial: "175", countryId: "Cross River", id: "Abi" },
    { serial: "176", countryId: "Cross River", id: "Ikom" },
    { serial: "177", countryId: "Cross River", id: "Yarkur" },
    { serial: "178", countryId: "Cross River", id: "Odubra" },
    { serial: "179", countryId: "Cross River", id: "Boki" },
    { serial: "180", countryId: "Cross River", id: "Ogoja" },
    { serial: "181", countryId: "Cross River", id: "Yala" },
    { serial: "182", countryId: "Cross River", id: "Obanliku" },
    { serial: "183", countryId: "Cross River", id: "Obudu" },
    { serial: "184", countryId: "Cross River", id: "Calabar South" },
    { serial: "185", countryId: "Cross River", id: "Etung" },
    { serial: "186", countryId: "Cross River", id: "Bekwara" },
    { serial: "187", countryId: "Cross River", id: "Bakassi" },
    { serial: "188", countryId: "Cross River", id: "Calabar Municipality" },
    { serial: "189", countryId: "Delta", id: "Oshimili" },
    { serial: "190", countryId: "Delta", id: "Aniocha" },
    { serial: "191", countryId: "Delta", id: "Aniocha South" },
    { serial: "192", countryId: "Delta", id: "Ika South" },
    { serial: "193", countryId: "Delta", id: "Ika North-East" },
    { serial: "194", countryId: "Delta", id: "Ndokwa West" },
    { serial: "195", countryId: "Delta", id: "Ndokwa East" },
    { serial: "196", countryId: "Delta", id: "Isoko South" },
    { serial: "197", countryId: "Delta", id: "Isoko North" },
    { serial: "198", countryId: "Delta", id: "Bomadi" },
    { serial: "199", countryId: "Delta", id: "Burutu" },
    { serial: "200", countryId: "Delta", id: "Ughelli South" },
    { serial: "201", countryId: "Delta", id: "Ughelli North" },
    { serial: "202", countryId: "Delta", id: "Ethiope West" },
    { serial: "203", countryId: "Delta", id: "Ethiope East" },
    { serial: "204", countryId: "Delta", id: "Sapele" },
    { serial: "205", countryId: "Delta", id: "Okpe" },
    { serial: "206", countryId: "Delta", id: "Warri Central" },
    { serial: "207", countryId: "Delta", id: "Warri North" },
    { serial: "208", countryId: "Delta", id: "Warri South" },
    { serial: "209", countryId: "Delta", id: "Udu" },
    { serial: "210", countryId: "Delta", id: "Ukwani" },
    { serial: "211", countryId: "Delta", id: "Uvwie" },
    { serial: "212", countryId: "Delta", id: "Oshimili North" },
    { serial: "213", countryId: "Delta", id: "Patani" },
    { serial: "214", countryId: "Ebonyi", id: "Edda" },
    { serial: "215", countryId: "Ebonyi", id: "Afikpo" },
    { serial: "216", countryId: "Ebonyi", id: "Onicha" },
    { serial: "217", countryId: "Ebonyi", id: "Ohaozara" },
    { serial: "218", countryId: "Ebonyi", id: "Abakaliki" },
    { serial: "219", countryId: "Ebonyi", id: "Ishielu" },
    { serial: "220", countryId: "Ebonyi", id: "Ikwo" },
    { serial: "221", countryId: "Ebonyi", id: "Ezza" },
    { serial: "222", countryId: "Ebonyi", id: "Ezza South" },
    { serial: "221", countryId: "Ebonyi", id: "Ohaukwu" },
    { serial: "223", countryId: "Ebonyi", id: "Ebonyi" },
    { serial: "224", countryId: "Ebonyi", id: "Ivo" },
    { serial: "226", countryId: "Edo", id: "Enugu South" },
    { serial: "227", countryId: "Edo", id: "Igbo-Eze South" },
    { serial: "225", countryId: "Edo", id: "Enugu North" },
    { serial: "228", countryId: "Edo", id: "Nkanu" },
    { serial: "229", countryId: "Edo", id: "Udi-Agwu" },
    { serial: "230", countryId: "Edo", id: "Oji River" },
    { serial: "231", countryId: "Edo", id: "Ezeagu" },
    { serial: "232", countryId: "Edo", id: "Igbo-Eze North" },
    { serial: "233", countryId: "Edo", id: "Isi-Uzo" },
    { serial: "234", countryId: "Edo", id: "Nsukka" },
    { serial: "235", countryId: "Edo", id: "Igbo-Ekiti" },
    { serial: "236", countryId: "Edo", id: "Uzo-Uwani" },
    { serial: "237", countryId: "Edo", id: "Enugu East" },
    { serial: "238", countryId: "Edo", id: "Aninri" },
    { serial: "239", countryId: "Edo", id: "Nkanu East" },
    { serial: "240", countryId: "Edo", id: "Udenu" },
    { serial: "241", countryId: "Ekiti", id: "Esan North-East" },
    { serial: "242", countryId: "Ekiti", id: "Esan Central" },
    { serial: "243", countryId: "Ekiti", id: "Esan West" },
    { serial: "244", countryId: "Ekiti", id: "Esan South-East" },
    { serial: "245", countryId: "Ekiti", id: "Etsako Central" },
    { serial: "246", countryId: "Ekiti", id: "Etsako East" },
    { serial: "247", countryId: "Ekiti", id: "Egor" },
    { serial: "248", countryId: "Ekiti", id: "Ukpoba" },
    { serial: "249", countryId: "Ekiti", id: "Central" },
    { serial: "250", countryId: "Ekiti", id: "Igueben" },
    { serial: "251", countryId: "Ekiti", id: "Oredo" },
    { serial: "252", countryId: "Ekiti", id: "Ovia South-West" },
    { serial: "253", countryId: "Ekiti", id: "Ovia South-East" },
    { serial: "254", countryId: "Ekiti", id: "Orhionwon" },
    { serial: "255", countryId: "Ekiti", id: "Uhunmwonde" },
    { serial: "256", countryId: "Enugu", id: "Ado" },
    { serial: "257", countryId: "Enugu", id: "Ekiti East" },
    { serial: "258", countryId: "Enugu", id: "Ekiti West" },
    { serial: "259", countryId: "Enugu", id: "Ekiti South-West" },
    { serial: "260", countryId: "Enugu", id: "Emure/Ise/Orun" },
    { serial: "261", countryId: "Enugu", id: "Ikere" },
    { serial: "262", countryId: "Enugu", id: "Irepodun" },
    { serial: "263", countryId: "Enugu", id: "Ijero" },
    { serial: "264", countryId: "Enugu", id: "Ido/Osi" },
    { serial: "265", countryId: "Enugu", id: "Oye" },
    { serial: "266", countryId: "Enugu", id: "Ikole" },
    { serial: "267", countryId: "Enugu", id: "Moba" },
    { serial: "268", countryId: "Enugu", id: "Gbonyin" },
    { serial: "269", countryId: "Enugu", id: "Efon" },
    { serial: "270", countryId: "Enugu", id: "Ise/Orun" },
    { serial: "271", countryId: "Enugu", id: "Ilejemeje" },
    { serial: "272", countryId: "FCT - Abuja", id: "Abaji" },
    { serial: "273", countryId: "FCT - Abuja", id: "Abuja Municipal" },
    { serial: "274", countryId: "FCT - Abuja", id: "Bwari" },
    { serial: "275", countryId: "FCT - Abuja", id: "Gwagwalada" },
    { serial: "276", countryId: "FCT - Abuja", id: "Kuje" },
    { serial: "277", countryId: "FCT - Abuja", id: "Kwali" },
    { serial: "278", countryId: "Gombe", id: "Akko" },
    { serial: "279", countryId: "Gombe", id: "Balanga" },
    { serial: "280", countryId: "Gombe", id: "Billiri" },
    { serial: "281", countryId: "Gombe", id: "Dukku" },
    { serial: "282", countryId: "Gombe", id: "Kaltungo" },
    { serial: "283", countryId: "Gombe", id: "Kwami" },
    { serial: "284", countryId: "Gombe", id: "Shomgom" },
    { serial: "285", countryId: "Gombe", id: "Funakaye" },
    { serial: "286", countryId: "Gombe", id: "Gombe" },
    { serial: "287", countryId: "Gombe", id: "Nafada/Bajoga" },
    { serial: "288", countryId: "Gombe", id: "Yamaltu/Delta" },
    { serial: "289", countryId: "Imo", id: "Aboh-Mbaise" },
    { serial: "290", countryId: "Imo", id: "Ahiazu-Mbaise" },
    { serial: "291", countryId: "Imo", id: "Ehime-Mbano" },
    { serial: "292", countryId: "Imo", id: "Ezinihitte" },
    { serial: "293", countryId: "Imo", id: "Ideato North" },
    { serial: "294", countryId: "Imo", id: "Ideato South" },
    { serial: "295", countryId: "Imo", id: "Ihitte/Uboma" },
    { serial: "296", countryId: "Imo", id: "Ikeduru" },
    { serial: "297", countryId: "Imo", id: "Isiala Mbano" },
    { serial: "298", countryId: "Imo", id: "Isu" },
    { serial: "299", countryId: "Imo", id: "Mbaitoli" },
    { serial: "300", countryId: "Imo", id: "Ngor-Okpala" },
    { serial: "301", countryId: "Imo", id: "Njaba" },
    { serial: "302", countryId: "Imo", id: "Nwangele" },
    { serial: "303", countryId: "Imo", id: "Nkwerre" },
    { serial: "304", countryId: "Imo", id: "Obowo" },
    { serial: "305", countryId: "Imo", id: "Oguta" },
    { serial: "306", countryId: "Imo", id: "Ohaji/Egbema" },
    { serial: "307", countryId: "Imo", id: "Okigwe" },
    { serial: "308", countryId: "Imo", id: "Orlu" },
    { serial: "309", countryId: "Imo", id: "Orsu" },
    { serial: "310", countryId: "Imo", id: "Oru East" },
    { serial: "311", countryId: "Imo", id: "Oru West" },
    { serial: "312", countryId: "Imo", id: "Owerri Municipal" },
    { serial: "313", countryId: "Imo", id: "Owerri North" },
    { serial: "314", countryId: "Imo", id: "Owerri West" },
    { serial: "315", countryId: "Jigawa", id: "Auyo" },
    { serial: "316", countryId: "Jigawa", id: "Babura" },
    { serial: "317", countryId: "Jigawa", id: "Birni Kudu" },
    { serial: "318", countryId: "Jigawa", id: "Birniwa" },
    { serial: "319", countryId: "Jigawa", id: "Buji" },
    { serial: "320", countryId: "Jigawa", id: "Dutse" },
    { serial: "321", countryId: "Jigawa", id: "Gagarawa" },
    { serial: "322", countryId: "Jigawa", id: "Garki" },
    { serial: "323", countryId: "Jigawa", id: "Gumel" },
    { serial: "324", countryId: "Jigawa", id: "Guri" },
    { serial: "325", countryId: "Jigawa", id: "Gwaram" },
    { serial: "326", countryId: "Jigawa", id: "Gwiwa" },
    { serial: "327", countryId: "Jigawa", id: "Hadejia" },
    { serial: "328", countryId: "Jigawa", id: "Jahun" },
    { serial: "329", countryId: "Jigawa", id: "Kafin Hausa" },
    { serial: "330", countryId: "Jigawa", id: "Kaugama Kazaure" },
    { serial: "331", countryId: "Jigawa", id: "Kiri Kasamma" },
    { serial: "332", countryId: "Jigawa", id: "Kiyawa" },
    { serial: "333", countryId: "Jigawa", id: "Maigatari" },
    { serial: "334", countryId: "Jigawa", id: "Malam Madori" },
    { serial: "335", countryId: "Jigawa", id: "Miga" },
    { serial: "336", countryId: "Jigawa", id: "Ringim" },
    { serial: "337", countryId: "Jigawa", id: "Roni" },
    { serial: "338", countryId: "Jigawa", id: "Sule-Tankarkar" },
    { serial: "339", countryId: "Jigawa", id: "Taura" },
    { serial: "340", countryId: "Jigawa", id: "Yankwashi" },
    { serial: "341", countryId: "Kaduna", id: "Birni-Gwari" },
    { serial: "342", countryId: "Kaduna", id: "Chikun" },
    { serial: "343", countryId: "Kaduna", id: "Giwa" },
    { serial: "344", countryId: "Kaduna", id: "Igabi" },
    { serial: "345", countryId: "Kaduna", id: "Ikara" },
    { serial: "346", countryId: "Kaduna", id: "Jaba" },
    { serial: "347", countryId: "Kaduna", id: "Jema'a" },
    { serial: "348", countryId: "Kaduna", id: "Kachia" },
    { serial: "349", countryId: "Kaduna", id: "Kaduna North" },
    { serial: "350", countryId: "Kaduna", id: "Kaduna South" },
    { serial: "351", countryId: "Kaduna", id: "Kagarko" },
    { serial: "352", countryId: "Kaduna", id: "Kajuru" },
    { serial: "353", countryId: "Kaduna", id: "Kaura" },
    { serial: "354", countryId: "Kaduna", id: "Kauru" },
    { serial: "355", countryId: "Kaduna", id: "Kubau" },
    { serial: "356", countryId: "Kaduna", id: "Kudan" },
    { serial: "357", countryId: "Kaduna", id: "Lere" },
    { serial: "358", countryId: "Kaduna", id: "Makarfi" },
    { serial: "359", countryId: "Kaduna", id: "Sabon-Gari" },
    { serial: "360", countryId: "Kaduna", id: "Sanga" },
    { serial: "361", countryId: "Kaduna", id: "Soba" },
    { serial: "362", countryId: "Kaduna", id: "Zango-Kataf" },
    { serial: "363", countryId: "Kaduna", id: "Ajingi" },
    { serial: "364", countryId: "Kano", id: "Albasu" },
    { serial: "365", countryId: "Kano", id: "Bagwai" },
    { serial: "366", countryId: "Kano", id: "Bebeji" },
    { serial: "367", countryId: "Kano", id: "Bichi" },
    { serial: "368", countryId: "Kano", id: "Bunkure" },
    { serial: "369", countryId: "Kano", id: "Dala" },
    { serial: "370", countryId: "Kano", id: "Dambatta" },
    { serial: "371", countryId: "Kano", id: "Dawakin Kudu" },
    { serial: "372", countryId: "Kano", id: "Dawakin Tofa" },
    { serial: "373", countryId: "Kano", id: "Doguwa" },
    { serial: "374", countryId: "Kano", id: "Fagge" },
    { serial: "375", countryId: "Kano", id: "Gabasawa" },
    { serial: "376", countryId: "Kano", id: "Garko" },
    { serial: "377", countryId: "Kano", id: "Garum" },
    { serial: "378", countryId: "Kano", id: "Mallam" },
    { serial: "379", countryId: "Kano", id: "Gaya" },
    { serial: "380", countryId: "Kano", id: "Gezawa" },
    { serial: "381", countryId: "Kano", id: "Gwale" },
    { serial: "382", countryId: "Kano", id: "Gwarzo" },
    { serial: "383", countryId: "Kano", id: "Kabo" },
    { serial: "384", countryId: "Kano", id: "Kano Municipal" },
    { serial: "385", countryId: "Kano", id: "Karaye" },
    { serial: "386", countryId: "Kano", id: "Kibiya" },
    { serial: "387", countryId: "Kano", id: "Kiru" },
    { serial: "388", countryId: "Kano", id: "Kumbotso" },
    { serial: "389", countryId: "Kano", id: "Ghari" },
    { serial: "390", countryId: "Kano", id: "Kura" },
    { serial: "391", countryId: "Kano", id: "Madobi" },
    { serial: "392", countryId: "Kano", id: "Makoda" },
    { serial: "393", countryId: "Kano", id: "Minjibir" },
    { serial: "394", countryId: "Kano", id: "Nasarawa" },
    { serial: "395", countryId: "Kano", id: "Rano" },
    { serial: "396", countryId: "Kano", id: "Rimin Gado" },
    { serial: "397", countryId: "Kano", id: "Rogo" },
    { serial: "398", countryId: "Kano", id: "Shanono" },
    { serial: "399", countryId: "Kano", id: "Sumaila" },
    { serial: "400", countryId: "Kano", id: "Takali" },
    { serial: "401", countryId: "Kano", id: "Tarauni" },
    { serial: "402", countryId: "Kano", id: "Tofa" },
    { serial: "403", countryId: "Kano", id: "Tsanyawa" },
    { serial: "404", countryId: "Kano", id: "Tudun Wada" },
    { serial: "405", countryId: "Kano", id: "Ungogo" },
    { serial: "406", countryId: "Kano", id: "Warawa" },
    { serial: "407", countryId: "Kano", id: "Wudil" },
    { serial: "408", countryId: "Katsina", id: "Bakori" },
    { serial: "409", countryId: "Katsina", id: "Batagarawa" },
    { serial: "410", countryId: "Katsina", id: "Batsari" },
    { serial: "411", countryId: "Katsina", id: "Baure" },
    { serial: "412", countryId: "Katsina", id: "Bindawa" },
    { serial: "413", countryId: "Katsina", id: "Charanchi" },
    { serial: "414", countryId: "Katsina", id: "Dandume" },
    { serial: "415", countryId: "Katsina", id: "Danja" },
    { serial: "416", countryId: "Katsina", id: "Dan Musa" },
    { serial: "417", countryId: "Katsina", id: "Daura" },
    { serial: "418", countryId: "Katsina", id: "Dutsi" },
    { serial: "419", countryId: "Katsina", id: "Dutsin-Ma" },
    { serial: "420", countryId: "Katsina", id: "Faskari" },
    { serial: "421", countryId: "Katsina", id: "Funtua" },
    { serial: "422", countryId: "Katsina", id: "Ingawa" },
    { serial: "423", countryId: "Katsina", id: "Jibia" },
    { serial: "424", countryId: "Katsina", id: "Kafur" },
    { serial: "425", countryId: "Katsina", id: "Kaita" },
    { serial: "426", countryId: "Katsina", id: "Kankara" },
    { serial: "427", countryId: "Katsina", id: "Kankia" },
    { serial: "428", countryId: "Katsina", id: "Katsina" },
    { serial: "429", countryId: "Katsina", id: "Kurfi" },
    { serial: "430", countryId: "Katsina", id: "Kusada" },
    { serial: "431", countryId: "Katsina", id: "Mai'Adua" },
    { serial: "432", countryId: "Katsina", id: "Malumfashi" },
    { serial: "433", countryId: "Katsina", id: "Mani" },
    { serial: "434", countryId: "Katsina", id: "Mashi" },
    { serial: "435", countryId: "Katsina", id: "Matazuu" },
    { serial: "436", countryId: "Katsina", id: "Musawa" },
    { serial: "437", countryId: "Katsina", id: "Rimi" },
    { serial: "438", countryId: "Katsina", id: "Sabuwa" },
    { serial: "439", countryId: "Katsina", id: "Safana" },
    { serial: "440", countryId: "Katsina", id: "Sandamu" },
    { serial: "441", countryId: "Katsina", id: "Zango" },
    { serial: "442", countryId: "Kebbi", id: "Aleiro" },
    { serial: "443", countryId: "Kebbi", id: "Arewa-Dandi" },
    { serial: "444", countryId: "Kebbi", id: "Argungu" },
    { serial: "445", countryId: "Kebbi", id: "Augie" },
    { serial: "446", countryId: "Kebbi", id: "Bagudo" },
    { serial: "447", countryId: "Kebbi", id: "Birnin Kebbi" },
    { serial: "448", countryId: "Kebbi", id: "Bunza" },
    { serial: "449", countryId: "Kebbi", id: "Dandi" },
    { serial: "450", countryId: "Kebbi", id: "Fakai" },
    { serial: "451", countryId: "Kebbi", id: "Gwandu" },
    { serial: "452", countryId: "Kebbi", id: "Jega" },
    { serial: "453", countryId: "Kebbi", id: "Kalgo" },
    { serial: "454", countryId: "Kebbi", id: "Koko/Besse" },
    { serial: "455", countryId: "Kebbi", id: "Maiyama" },
    { serial: "456", countryId: "Kebbi", id: "Ngaski" },
    { serial: "457", countryId: "Kebbi", id: "Sakaba" },
    { serial: "458", countryId: "Kebbi", id: "Shanga" },
    { serial: "459", countryId: "Kebbi", id: "Suru" },
    { serial: "460", countryId: "Kebbi", id: "Wasagu/Danko" },
    { serial: "461", countryId: "Kebbi", id: "Yauri" },
    { serial: "462", countryId: "Kebbi", id: "Zuru" },
    { serial: "463", countryId: "Kogi", id: "Adavi" },
    { serial: "464", countryId: "Kogi", id: "Ajaokuta" },
    { serial: "465", countryId: "Kogi", id: "Ankpa" },
    { serial: "466", countryId: "Kogi", id: "Bassa" },
    { serial: "467", countryId: "Kogi", id: "Dekina" },
    { serial: "468", countryId: "Kogi", id: "Ibaji" },
    { serial: "469", countryId: "Kogi", id: "Idah" },
    { serial: "470", countryId: "Kogi", id: "Igalamela-Odolu" },
    { serial: "471", countryId: "Kogi", id: "Ijumu" },
    { serial: "472", countryId: "Kogi", id: "Kabba/Bunu" },
    { serial: "473", countryId: "Kogi", id: "Kogi" },
    { serial: "474", countryId: "Kogi", id: "Lokoja" },
    { serial: "475", countryId: "Kogi", id: "Mopa-Muro" },
    { serial: "476", countryId: "Kogi", id: "Ofu" },
    { serial: "477", countryId: "Kogi", id: "Ogori/Mangongo" },
    { serial: "478", countryId: "Kogi", id: "Okehi" },
    { serial: "479", countryId: "Kogi", id: "Okene" },
    { serial: "480", countryId: "Kogi", id: "Olamabolo" },
    { serial: "481", countryId: "Kogi", id: "Omala" },
    { serial: "482", countryId: "Kogi", id: "Yagba East" },
    { serial: "483", countryId: "Kogi", id: "Yagba West" },
    { serial: "484", countryId: "Kwara", id: "Asa" },
    { serial: "485", countryId: "Kwara", id: "Baruten" },
    { serial: "486", countryId: "Kwara", id: "Edu" },
    { serial: "487", countryId: "Kwara", id: "Ekiti" },
    { serial: "488", countryId: "Kwara", id: "Ifelodun" },
    { serial: "489", countryId: "Kwara", id: "Ilorin East" },
    { serial: "490", countryId: "Kwara", id: "Ilorin West" },
    { serial: "491", countryId: "Kwara", id: "Irepodun" },
    { serial: "492", countryId: "Kwara", id: "Isin" },
    { serial: "493", countryId: "Kwara", id: "Kaiama" },
    { serial: "494", countryId: "Kwara", id: "Moro" },
    { serial: "495", countryId: "Kwara", id: "Offa" },
    { serial: "496", countryId: "Kwara", id: "Oke-Ero" },
    { serial: "497", countryId: "Kwara", id: "Oyun" },
    { serial: "498", countryId: "Kwara", id: "Pategi" },
    { serial: "499", countryId: "Lagos", id: "Agege LGA: Agege LCDA" },
    { serial: "500", countryId: "Lagos", id: "Agege LGA: Orile-Agege LCDA" },
    {
      serial: "501",
      countryId: "Lagos",
      id: "Ajeromi/Ifelodun LGA: Ajeromi LCDA",
    },
    {
      serial: "502",
      countryId: "Lagos",
      id: "Ajeromi/Ifelodun LGA: Ifelodun LCDA",
    },
    { serial: "503", countryId: "Lagos", id: "Alimosho LGA: Alimosho LCDA" },
    {
      serial: "504",
      countryId: "Lagos",
      id: "Alimosho LGA: Agbado/Oke-Odo LCDA",
    },
    { serial: "505", countryId: "Lagos", id: "Alimosho LGA: Ayobo-Ipaja LCDA" },
    { serial: "506", countryId: "Lagos", id: "Alimosho LGA: Egbe-Idimu LCDA" },
    {
      serial: "507",
      countryId: "Lagos",
      id: "Alimosho LGA: Igando-Ikotun LCDA",
    },
    {
      serial: "508",
      countryId: "Lagos",
      id: "Alimosho LGA: Mosan Okunola LCDA",
    },
    {
      serial: "509",
      countryId: "Lagos",
      id: "Amuwo-Odofin LGA: Amuwo-Odofin LCDA",
    },
    { serial: "510", countryId: "Lagos", id: "Amuwo-Odofin LGA: Oriade LCDA" },
    { serial: "511", countryId: "Lagos", id: "Apapa LGA: Apapa LCDA" },
    { serial: "512", countryId: "Lagos", id: "Apapa LGA: Apapa Iganmu LCDA" },
    { serial: "513", countryId: "Lagos", id: "Badagry LGA: Badagry LCDA" },
    { serial: "514", countryId: "Lagos", id: "Badagry LGA: Badagry West LCDA" },
    { serial: "515", countryId: "Lagos", id: "Badagry LGA: Olorunda LCDA" },
    { serial: "516", countryId: "Lagos", id: "Epe LGA: Epe LCDA" },
    { serial: "517", countryId: "Lagos", id: "Epe LGA: Eredo LCDA" },
    { serial: "518", countryId: "Lagos", id: "Epe LGA: Ikosi-Ejinrin LCDA" },
    { serial: "519", countryId: "Lagos", id: "Eti-Osa LGA: Eti-Osa East LCDA" },
    { serial: "520", countryId: "Lagos", id: "Eti-Osa LGA: Eti-Osa West LCDA" },
    {
      serial: "521",
      countryId: "Lagos",
      id: "Eti-Osa LGA: Iru-Victoria Island LCDA",
    },
    {
      serial: "522",
      countryId: "Lagos",
      id: "Eti-Osa LGA: Ikoyi-Obalende LCDA",
    },
    { serial: "523", countryId: "Lagos", id: "Ibeju-Lekki LGA: Ibeju LCDA" },
    { serial: "524", countryId: "Lagos", id: "Ibeju Lekki LGA: Lekki LCDA" },
    {
      serial: "525",
      countryId: "Lagos",
      id: "Ifako/Ijaiye LGA: Ifako/Ijaiye LCDA",
    },
    { serial: "526", countryId: "Lagos", id: "Ifako-Ijaiye LGA: Ojokoro LCDA" },
    { serial: "527", countryId: "Lagos", id: "Ikeja LGA: Ikeja LCDA" },
    { serial: "528", countryId: "Lagos", id: "Ikeja LGA: Ojodu LCDA" },
    { serial: "529", countryId: "Lagos", id: "Ikeja LGA: Onigbongbo" },
    { serial: "530", countryId: "Lagos", id: "Ikorodu LGA: Ikorodu LCDA" },
    {
      serial: "531",
      countryId: "Lagos",
      id: "Ikorodu LGA: Ikorodu North LCDA",
    },
    { serial: "532", countryId: "Lagos", id: "Ikorodu LGA: Ikorodu West LCDA" },
    { serial: "533", countryId: "Lagos", id: "Ikorodu LGA: Imota LCDA" },
    { serial: "534", countryId: "Lagos", id: "Ikorodu LGA: Ijede LCDA" },
    {
      serial: "535",
      countryId: "Lagos",
      id: "Ikorodu LGA: Igbogbo-Baiyeku LCDA",
    },
    { serial: "536", countryId: "Lagos", id: "Kosofe LGA: Kosofe LCDA" },
    { serial: "537", countryId: "Lagos", id: "Kosofe LGA: Ikosi-Isheri LCDA" },
    { serial: "538", countryId: "Lagos", id: "Kosofe LGA: Agboyi-Ketu LCDA" },
    {
      serial: "539",
      countryId: "Lagos",
      id: "Lagos Island LGA: Lagos Island East LCDA",
    },
    {
      serial: "540",
      countryId: "Lagos",
      id: "Lagos Island LGA: Lagos Island West LCDA",
    },
    {
      serial: "541",
      countryId: "Lagos",
      id: "Lagos Mainland LGA: Lagos Mainland LCDA",
    },
    { serial: "542", countryId: "Lagos", id: "Lagos Mainland LGA: Yaba LCDA" },
    { serial: "543", countryId: "Lagos", id: "Mushin LGA: Mushin LCDA" },
    { serial: "544", countryId: "Lagos", id: "Mushin LGA: Odi-Olowo LCDA" },
    { serial: "545", countryId: "Lagos", id: "Ojo LGA: Ojo LCDA" },
    { serial: "546", countryId: "Lagos", id: "Ojo LGA: Oto-Awori LCDA" },
    { serial: "547", countryId: "Lagos", id: "Ojo LGA: Iba LCDA" },
    { serial: "548", countryId: "Lagos", id: "Shomolu LGA: Shomolu LCDA" },
    { serial: "549", countryId: "Lagos", id: "Shomolu LGA: Bariga LCDA" },
    { serial: "550", countryId: "Lagos", id: "Oshodi/Isolo LGA: Ejigbo LCDA" },
    { serial: "551", countryId: "Lagos", id: "Oshodi/Isolo LGA: Isolo LCDA" },
    { serial: "552", countryId: "Lagos", id: "Oshodi/Isolo LGA: Oshodi LCDA" },
    { serial: "553", countryId: "Lagos", id: "Surulere LGA: Surulere LCDA" },
    { serial: "554", countryId: "Lagos", id: "Surulere LGA: Coker Aguda LCDA" },
    { serial: "555", countryId: "Lagos", id: "Surulere LGA: Itire-Ikate LCDA" },
    { serial: "556", countryId: "Nasarawa", id: "Akwanga" },
    { serial: "557", countryId: "Nasarawa", id: "Awe" },
    { serial: "558", countryId: "Nasarawa", id: "Doma" },
    { serial: "559", countryId: "Nasarawa", id: "Karu" },
    { serial: "560", countryId: "Nasarawa", id: "Keana" },
    { serial: "561", countryId: "Nasarawa", id: "Keffi" },
    { serial: "562", countryId: "Nasarawa", id: "Kokona" },
    { serial: "563", countryId: "Nasarawa", id: "Lafia" },
    { serial: "564", countryId: "Nasarawa", id: "Nasarawa" },
    { serial: "565", countryId: "Nasarawa", id: "Nasarawa-Eggon" },
    { serial: "566", countryId: "Nasarawa", id: "Obi" },
    { serial: "567", countryId: "Nasarawa", id: "Toto" },
    { serial: "568", countryId: "Nasarawa", id: "Wambe" },
    { serial: "569", countryId: "Niger", id: "Agaie" },
    { serial: "570", countryId: "Niger", id: "Agwara" },
    { serial: "571", countryId: "Niger", id: "Bida" },
    { serial: "572", countryId: "Niger", id: "Borgu" },
    { serial: "573", countryId: "Niger", id: "Bosso" },
    { serial: "574", countryId: "Niger", id: "Chanchaga" },
    { serial: "575", countryId: "Niger", id: "Edati" },
    { serial: "576", countryId: "Niger", id: "Gbako" },
    { serial: "577", countryId: "Niger", id: "Gurara" },
    { serial: "578", countryId: "Niger", id: "Tafa" },
    { serial: "579", countryId: "Niger", id: "Katcha" },
    { serial: "580", countryId: "Niger", id: "Kontagora" },
    { serial: "581", countryId: "Niger", id: "Lapai" },
    { serial: "582", countryId: "Niger", id: "Lavun" },
    { serial: "583", countryId: "Niger", id: "Magama" },
    { serial: "584", countryId: "Niger", id: "Mariga" },
    { serial: "585", countryId: "Niger", id: "Mashegu" },
    { serial: "586", countryId: "Niger", id: "Mokwa" },
    { serial: "587", countryId: "Niger", id: "Muya" },
    { serial: "588", countryId: "Niger", id: "Pailoro" },
    { serial: "589", countryId: "Niger", id: "Rafi" },
    { serial: "590", countryId: "Niger", id: "Rijau" },
    { serial: "591", countryId: "Niger", id: "Shiroro" },
    { serial: "592", countryId: "Niger", id: "Suleja" },
    { serial: "593", countryId: "Niger", id: "Wushishi" },
    { serial: "594", countryId: "Ogun", id: "Abeokuta North" },
    { serial: "595", countryId: "Ogun", id: "Abeokuta South" },
    { serial: "596", countryId: "Ogun", id: "Ado-Odo/Ota" },
    { serial: "597", countryId: "Ogun", id: "Yewa North" },
    { serial: "598", countryId: "Ogun", id: "Yewa South" },
    { serial: "599", countryId: "Ogun", id: "Ewekoro" },
    { serial: "600", countryId: "Ogun", id: "Ifo" },
    { serial: "601", countryId: "Ogun", id: "Ijebu East" },
    { serial: "602", countryId: "Ogun", id: "Ijebu North" },
    { serial: "603", countryId: "Ogun", id: "Ijebu North East" },
    { serial: "604", countryId: "Ogun", id: "Ijebu Ode" },
    { serial: "605", countryId: "Ogun", id: "Ikenne" },
    { serial: "606", countryId: "Ogun", id: "Imeko-Afon" },
    { serial: "607", countryId: "Ogun", id: "Ipokia" },
    { serial: "608", countryId: "Ogun", id: "Obafemi-Owode" },
    { serial: "609", countryId: "Ogun", id: "Ogun Waterside" },
    { serial: "610", countryId: "Ogun", id: "Odeda" },
    { serial: "611", countryId: "Ogun", id: "Odogbolu" },
    { serial: "612", countryId: "Ogun", id: "Remo North" },
    { serial: "613", countryId: "Ogun", id: "Shagamu" },
    { serial: "614", countryId: "Ondo", id: "Akoko North-East" },
    { serial: "615", countryId: "Ondo", id: "Akoko North-West" },
    { serial: "616", countryId: "Ondo", id: "Akoko South" },
    { serial: "617", countryId: "Ondo", id: "Akoko South-West" },
    { serial: "618", countryId: "Ondo", id: "Akure East" },
    { serial: "619", countryId: "Ondo", id: "Akure North" },
    { serial: "620", countryId: "Ondo", id: "Akure South" },
    { serial: "621", countryId: "Ondo", id: "Ese-Odo" },
    { serial: "622", countryId: "Ondo", id: "Idanre" },
    { serial: "623", countryId: "Ondo", id: "Ifedore" },
    { serial: "624", countryId: "Ondo", id: "Ilaje" },
    { serial: "625", countryId: "Ondo", id: "Ile-Oluji" },
    { serial: "626", countryId: "Ondo", id: "Okeigbo" },
    { serial: "627", countryId: "Ondo", id: "Irele" },
    { serial: "628", countryId: "Ondo", id: "Okitipupa" },
    { serial: "629", countryId: "Ondo", id: "Ondo East" },
    { serial: "630", countryId: "Ondo", id: "Ondo West" },
    { serial: "631", countryId: "Ondo", id: "Odigbo" },
    { serial: "632", countryId: "Ondo", id: "Ose" },
    { serial: "633", countryId: "Ondo", id: "Owo" },
    { serial: "634", countryId: "Osun", id: "Aiyedade" },
    { serial: "635", countryId: "Osun", id: "Aiyedire" },
    { serial: "636", countryId: "Osun", id: "Atakumosa East" },
    { serial: "637", countryId: "Osun", id: "Atakumosa West" },
    { serial: "638", countryId: "Osun", id: "Boluwaduro" },
    { serial: "639", countryId: "Osun", id: "Boripe" },
    { serial: "640", countryId: "Osun", id: "Ede North" },
    { serial: "641", countryId: "Osun", id: "Ede South" },
    { serial: "642", countryId: "Osun", id: "Egbedore" },
    { serial: "643", countryId: "Osun", id: "Ejigbo" },
    { serial: "644", countryId: "Osun", id: "Ife Central" },
    { serial: "645", countryId: "Osun", id: "Ife East" },
    { serial: "646", countryId: "Osun", id: "Ife North" },
    { serial: "647", countryId: "Osun", id: "Ife South" },
    { serial: "648", countryId: "Osun", id: "Ifedayo" },
    { serial: "649", countryId: "Osun", id: "Ifelodun" },
    { serial: "650", countryId: "Osun", id: "Ila" },
    { serial: "651", countryId: "Osun", id: "Ilesha East" },
    { serial: "652", countryId: "Osun", id: "Ilesha West" },
    { serial: "653", countryId: "Osun", id: "Irepodun" },
    { serial: "654", countryId: "Osun", id: "Irewole" },
    { serial: "655", countryId: "Osun", id: "Isokan" },
    { serial: "656", countryId: "Osun", id: "Iwo" },
    { serial: "657", countryId: "Osun", id: "Obokun" },
    { serial: "658", countryId: "Osun", id: "Odo-Otin" },
    { serial: "659", countryId: "Osun", id: "Ola-Oluwa" },
    { serial: "660", countryId: "Osun", id: "Olorunda" },
    { serial: "661", countryId: "Osun", id: "Oriade" },
    { serial: "662", countryId: "Osun", id: "Orolu" },
    { serial: "663", countryId: "Osun", id: "Osogbo" },
    { serial: "664", countryId: "Oyo", id: "Afijio" },
    { serial: "665", countryId: "Oyo", id: "Akinyele" },
    { serial: "666", countryId: "Oyo", id: "Ibadan Central" },
    { serial: "667", countryId: "Oyo", id: "Ibadan North" },
    { serial: "668", countryId: "Oyo", id: "Ibadan North-West" },
    { serial: "669", countryId: "Oyo", id: "Ibadan South-East" },
    { serial: "670", countryId: "Oyo", id: "Ibadan South-West" },
    { serial: "671", countryId: "Oyo", id: "Ibarapa Central" },
    { serial: "672", countryId: "Oyo", id: "Ibarapa East" },
    { serial: "673", countryId: "Oyo", id: "Ibarapa North" },
    { serial: "674", countryId: "Oyo", id: "Ido" },
    { serial: "675", countryId: "Oyo", id: "Irepo" },
    { serial: "676", countryId: "Oyo", id: "Iseyin" },
    { serial: "677", countryId: "Oyo", id: "Itesiwaju" },
    { serial: "678", countryId: "Oyo", id: "Iwajowa" },
    { serial: "679", countryId: "Oyo", id: "Kajola" },
    { serial: "680", countryId: "Oyo", id: "Lagelu Ogbomosho North" },
    { serial: "681", countryId: "Oyo", id: "Ogbomosho South" },
    { serial: "682", countryId: "Oyo", id: "Ogo Oluwa" },
    { serial: "683", countryId: "Oyo", id: "Olorunsogo" },
    { serial: "684", countryId: "Oyo", id: "Oluyole" },
    { serial: "685", countryId: "Oyo", id: "Ona-Ara" },
    { serial: "686", countryId: "Oyo", id: "Orelope" },
    { serial: "687", countryId: "Oyo", id: "Ori Ire" },
    { serial: "688", countryId: "Oyo", id: "Oyo East" },
    { serial: "689", countryId: "Oyo", id: "Oyo West" },
    { serial: "690", countryId: "Oyo", id: "Saki East" },
    { serial: "691", countryId: "Oyo", id: "Saki West" },
    { serial: "692", countryId: "Oyo", id: "Surulere" },
    { serial: "693", countryId: "Oyo", id: "Atiba" },
    { serial: "694", countryId: "Oyo", id: "Atisibo" },
    { serial: "695", countryId: "Oyo", id: "Egbeda" },
    { serial: "696", countryId: "Plateau", id: "Barikin Ladi" },
    { serial: "697", countryId: "Plateau", id: "Bassa" },
    { serial: "698", countryId: "Plateau", id: "Bokkos" },
    { serial: "699", countryId: "Plateau", id: "Jos East" },
    { serial: "700", countryId: "Plateau", id: "Jos North" },
    { serial: "701", countryId: "Plateau", id: "Jos South" },
    { serial: "702", countryId: "Plateau", id: "Kanam" },
    { serial: "703", countryId: "Plateau", id: "Kanke" },
    { serial: "704", countryId: "Plateau", id: "Langtang North" },
    { serial: "705", countryId: "Plateau", id: "Langtang South" },
    { serial: "706", countryId: "Plateau", id: "Mangu" },
    { serial: "707", countryId: "Plateau", id: "Mikang" },
    { serial: "708", countryId: "Plateau", id: "Pankshin" },
    { serial: "709", countryId: "Plateau", id: "Qua'an Pan" },
    { serial: "710", countryId: "Plateau", id: "Riyom" },
    { serial: "711", countryId: "Plateau", id: "Shendam" },
    { serial: "712", countryId: "Plateau", id: "Wase" },
    { serial: "713", countryId: "Rivers", id: "Abua/Odual" },
    { serial: "714", countryId: "Rivers", id: "Ahoada East" },
    { serial: "715", countryId: "Rivers", id: "Ahoada West" },
    { serial: "716", countryId: "Rivers", id: "Akuku Toru" },
    { serial: "717", countryId: "Rivers", id: "Andoni" },
    { serial: "718", countryId: "Rivers", id: "Asari-Toru" },
    { serial: "719", countryId: "Rivers", id: "Bonny" },
    { serial: "720", countryId: "Rivers", id: "Degema" },
    { serial: "721", countryId: "Rivers", id: "Emohua" },
    { serial: "722", countryId: "Rivers", id: "Eleme" },
    { serial: "723", countryId: "Rivers", id: "Etche" },
    { serial: "724", countryId: "Rivers", id: "Gokana" },
    { serial: "725", countryId: "Rivers", id: "Ikwerre" },
    { serial: "726", countryId: "Rivers", id: "Khana" },
    { serial: "727", countryId: "Rivers", id: "Obio/Akpor" },
    { serial: "728", countryId: "Rivers", id: "Ogba/Egbema/Ndoni" },
    { serial: "729", countryId: "Rivers", id: "Ogu/Bolo" },
    { serial: "730", countryId: "Rivers", id: "Okrika" },
    { serial: "731", countryId: "Rivers", id: "Omumma" },
    { serial: "732", countryId: "Rivers", id: "Opobo/Nkoro" },
    { serial: "733", countryId: "Rivers", id: "Oyigbo" },
    { serial: "734", countryId: "Rivers", id: "Port-Harcourt" },
    { serial: "735", countryId: "Rivers", id: "Tai" },
    { serial: "736", countryId: "Sokoto", id: "Binji" },
    { serial: "737", countryId: "Sokoto", id: "Bodinga" },
    { serial: "738", countryId: "Sokoto", id: "Dange-Shinsi" },
    { serial: "739", countryId: "Sokoto", id: "Gada" },
    { serial: "740", countryId: "Sokoto", id: "Goronyo" },
    { serial: "741", countryId: "Sokoto", id: "Gudu" },
    { serial: "742", countryId: "Sokoto", id: "Gawabawa" },
    { serial: "743", countryId: "Sokoto", id: "Illela" },
    { serial: "744", countryId: "Sokoto", id: "Isa" },
    { serial: "745", countryId: "Sokoto", id: "Kware" },
    { serial: "746", countryId: "Sokoto", id: "Kebbe" },
    { serial: "747", countryId: "Sokoto", id: "Rabah" },
    { serial: "748", countryId: "Sokoto", id: "Sabon Birni" },
    { serial: "749", countryId: "Sokoto", id: "Shagari" },
    { serial: "750", countryId: "Sokoto", id: "Silame" },
    { serial: "751", countryId: "Sokoto", id: "Sokoto North" },
    { serial: "752", countryId: "Sokoto", id: "Sokoto South" },
    { serial: "753", countryId: "Sokoto", id: "Tambuwal" },
    { serial: "754", countryId: "Sokoto", id: "Tangaza" },
    { serial: "755", countryId: "Sokoto", id: "Tureta" },
    { serial: "756", countryId: "Sokoto", id: "Wamako" },
    { serial: "757", countryId: "Sokoto", id: "Wurno" },
    { serial: "758", countryId: "Sokoto", id: "Yabo" },
    { serial: "759", countryId: "Taraba", id: "Ardo-Kola" },
    { serial: "760", countryId: "Taraba", id: "Bali" },
    { serial: "761", countryId: "Taraba", id: "Donga" },
    { serial: "762", countryId: "Taraba", id: "Gashaka" },
    { serial: "763", countryId: "Taraba", id: "Cassol" },
    { serial: "764", countryId: "Taraba", id: "Ibi" },
    { serial: "765", countryId: "Taraba", id: "Jalingo" },
    { serial: "766", countryId: "Taraba", id: "Karin-Lamido" },
    { serial: "767", countryId: "Taraba", id: "Kurmi" },
    { serial: "768", countryId: "Taraba", id: "Lau" },
    { serial: "769", countryId: "Taraba", id: "Sardauna" },
    { serial: "770", countryId: "Taraba", id: "Takum" },
    { serial: "771", countryId: "Taraba", id: "Ussa" },
    { serial: "772", countryId: "Taraba", id: "Wukari" },
    { serial: "773", countryId: "Taraba", id: "Yorro" },
    { serial: "774", countryId: "Taraba", id: "Zing" },
    { serial: "775", countryId: "Yobe", id: "Bade" },
    { serial: "776", countryId: "Yobe", id: "Bursari" },
    { serial: "777", countryId: "Yobe", id: "Damaturu" },
    { serial: "778", countryId: "Yobe", id: "Fika" },
    { serial: "779", countryId: "Yobe", id: "Fune" },
    { serial: "780", countryId: "Yobe", id: "Geidam" },
    { serial: "781", countryId: "Yobe", id: "Gujba" },
    { serial: "782", countryId: "Yobe", id: "Gulani" },
    { serial: "783", countryId: "Yobe", id: "Jakusko" },
    { serial: "784", countryId: "Yobe", id: "Karasuwa" },
    { serial: "785", countryId: "Yobe", id: "Karawa" },
    { serial: "786", countryId: "Yobe", id: "Machina" },
    { serial: "787", countryId: "Yobe", id: "Nangere" },
    { serial: "788", countryId: "Yobe", id: "Nguru Potiskum" },
    { serial: "789", countryId: "Yobe", id: "Tarmua" },
    { serial: "790", countryId: "Yobe", id: "Yunusari" },
    { serial: "791", countryId: "Yobe", id: "Yusufari" },
    { serial: "792", countryId: "Zamfara", id: "Anka" },
    { serial: "793", countryId: "Zamfara", id: "Bakura" },
    { serial: "794", countryId: "Zamfara", id: "Birnin Magaji" },
    { serial: "795", countryId: "Zamfara", id: "Bukkuyum" },
    { serial: "796", countryId: "Zamfara", id: "Bungudu" },
    { serial: "797", countryId: "Zamfara", id: "Gummi" },
    { serial: "798", countryId: "Zamfara", id: "Gusau" },
    { serial: "799", countryId: "Zamfara", id: "Kaura" },
    { serial: "800", countryId: "Zamfara", id: "Namoda" },
    { serial: "801", countryId: "Zamfara", id: "Maradun" },
    { serial: "802", countryId: "Zamfara", id: "Maru" },
    { serial: "803", countryId: "Zamfara", id: "Shinkafi" },
    { serial: "804", countryId: "Zamfara", id: "Talata Mafara" },
    { serial: "805", countryId: "Zamfara", id: "Tsafe" },
    { serial: "806", countryId: "Zamfara", id: "Zurmi" },
  ];
  const [country, setCountry] = useState([]);
  const [state, setState] = useState([]);

  useEffect(() => {
    setCountry(countries);
  }, []);

  const handleCountry = (id) => {
    const dt = states.filter((x) => x.countryId === id);
    setState(dt);
  };

  $(document).ready(function () {
    $("#inputBlock").hide();
    $("#selectLGA").change(function () {
      if ($(this).val() === "Select LGA") {
        $("#inputBlock").hide();
      } else {
        $("#inputBlock").show();
      }
    });
  });

  return (
    <div className="dropDown inputText">
      <div
        id="ddlCountry"
        className="formControl selectClass flex inputDiv"
        onChange={(e) => handleCountry(e.target.value)}
      >
        <GrMapLocation className="icon" />
        <input
          type="text"
          name="selectState"
          list="data"
          placeholder="Select State"
          id="inputField"
        />
        <datalist id="data">
          <option value="Select State">Select State</option>
          {country && country !== undefined
            ? country.map((ctr, index) => {
                return (
                  <option key={index} value={ctr.id}>
                    {ctr.id}
                  </option>
                );
              })
            : "No State"}
        </datalist>
        <label htmlFor="selectState">Select State</label>
      </div>

      <div id="ddlStates" className="formControl selectClass flex inputDiv">
        <GrMapLocation className="icon" />
        <input
          list="dataLGA"
          id="selectLGA"
          type="text"
          placeholder="Select LGA"
        />
        <datalist id="dataLGA">
          <option value="Select LGA">Select LGA</option>
          {state && state !== undefined
            ? state.map((ctr, index) => {
                return (
                  <option key={index} value={ctr.id}>
                    {ctr.id}
                  </option>
                );
              })
            : "No LGA"}
        </datalist>
        <label htmlFor="selectState">Select State</label>
      </div>

      <div id="inputBlock">
        <div className="flex inputDiv">
          <GrMapLocation className="icon" />
          <input
            type="text"
            id="detailedAddress"
            placeholder="1, Abc Street, Efg Busstop"
            aria-placeholder="Detailed Address"
            required
          />
          <label htmlFor="Detailed Address">Detailed Address</label>
        </div>
      </div>
    </div>
  );
}

export default NewLocation;
