import React, { useState, useEffect } from "react";
import "../ElectricBill.scss";
import "../../../../../App.scss";
import "./Location.scss";

function Location() {
  const countries = [
    { id: "1", name: "Abia" },
    { id: "2", name: "Adamawa" },
    { id: "3", name: "Akwa Ibom" },
    { id: "4", name: "Anambra" },
    { id: "5", name: "Bauchi" },
    { id: "6", name: "Bayelsa" },
    { id: "7", name: "Benue" },
    { id: "8", name: "Borno" },
    { id: "9", name: "Cross River" },
    { id: "10", name: "Delta" },
    { id: "11", name: "Ebonyi" },
    { id: "12", name: "Edo" },
    { id: "13", name: "Ekiti" },
    { id: "14", name: "Enugu" },
    { id: "15", name: "FCT - Abuja" },
    { id: "16", name: "Gombe" },
    { id: "17", name: "Imo" },
    { id: "18", name: "Jigawa" },
    { id: "19", name: "Kaduna" },
    { id: "20", name: "Kano" },
    { id: "21", name: "Katsina" },
    { id: "22", name: "Kebbi" },
    { id: "23", name: "Kogi" },
    { id: "24", name: "Kwara" },
    { id: "25", name: "Lagos" },
    { id: "26", name: "Nasarawa" },
    { id: "27", name: "Niger" },
    { id: "28", name: "Ogun" },
    { id: "29", name: "Ondo" },
    { id: "30", name: "Osun" },
    { id: "31", name: "Oyo" },
    { id: "32", name: "Plateau" },
    { id: "33", name: "Rivers" },
    { id: "34", name: "Sokoto" },
    { id: "35", name: "Taraba" },
    { id: "36", name: "Yobe" },
    { id: "37", name: "Zamfara" },
  ];

  const states = [
    { id: "1", countryId: "1", name: "Aba North" },
    { id: "2", countryId: "1", name: "Aba South" },
    { id: "3", countryId: "1", name: "Arochukwu" },
    { id: "4", countryId: "1", name: "Bende" },
    { id: "5", countryId: "1", name: "Ikwuano" },
    { id: "6", countryId: "1", name: "Isiala-Ngwa North" },
    { id: "7", countryId: "1", name: "Isiala-Ngwa South" },
    { id: "8", countryId: "1", name: "Isuikwuato" },
    { id: "9", countryId: "1", name: "Obi Nwa" },
    { id: "10", countryId: "1", name: "Ohafia" },
    { id: "11", countryId: "1", name: "Osisioma" },
    { id: "12", countryId: "1", name: "Ngwa" },
    { id: "13", countryId: "1", name: "Ugwunagbo" },
    { id: "14", countryId: "1", name: "Ukwa East" },
    { id: "15", countryId: "1", name: "Ukwa West" },
    { id: "16", countryId: "1", name: "Umuahia North" },
    { id: "17", countryId: "1", name: "Umuahia South" },
    { id: "18", countryId: "1", name: "Umu-Neochi" },
    { id: "19", countryId: "2", name: "Demsa" },
    { id: "20", countryId: "2", name: "Fufore" },
    { id: "21", countryId: "2", name: "Ganye" },
    { id: "22", countryId: "2", name: "Girei" },
    { id: "23", countryId: "2", name: "Gombi" },
    { id: "24", countryId: "2", name: "Guyuk" },
    { id: "25", countryId: "2", name: "Hong" },
    { id: "26", countryId: "2", name: "Jada" },
    { id: "27", countryId: "2", name: "Lamurde" },
    { id: "28", countryId: "2", name: "Madagali" },
    { id: "29", countryId: "2", name: "Maiha" },
    { id: "30", countryId: "2", name: "Mayo-Belwa" },
    { id: "31", countryId: "2", name: "Michika" },
    { id: "32", countryId: "2", name: "Mubi North" },
    { id: "33", countryId: "2", name: "Mubi South" },
    { id: "34", countryId: "2", name: "Numan" },
    { id: "35", countryId: "2", name: "Shelleng" },
    { id: "36", countryId: "2", name: "Song" },
    { id: "37", countryId: "2", name: "Toungo" },
    { id: "38", countryId: "2", name: "Yola North" },
    { id: "39", countryId: "2", name: "Yola South" },
    { id: "40", countryId: "3", name: "Aguata" },
    { id: "41", countryId: "3", name: "Anambra East" },
    { id: "42", countryId: "3", name: "Anambra West" },
    { id: "43", countryId: "3", name: "Anaocha" },
    { id: "44", countryId: "3", name: "Akwa North" },
    { id: "45", countryId: "3", name: "Akwa South" },
    { id: "46", countryId: "3", name: "Ayamelum" },
    { id: "47", countryId: "3", name: "Dunukofia" },
    { id: "48", countryId: "3", name: "Ekwusigo" },
    { id: "49", countryId: "3", name: "Idemili North" },
    { id: "50", countryId: "3", name: "Idemili South" },
    { id: "51", countryId: "3", name: "Ihiala" },
    { id: "52", countryId: "3", name: "Njikoka" },
    { id: "53", countryId: "3", name: "Nnewi North" },
    { id: "54", countryId: "3", name: "Nnewi South" },
    { id: "55", countryId: "3", name: "Ogbaru" },
    { id: "56", countryId: "3", name: "Onitsha North" },
    { id: "57", countryId: "3", name: "Onitsha South" },
    { id: "58", countryId: "3", name: "Orumba North" },
    { id: "59", countryId: "3", name: "Orumba South" },
    { id: "60", countryId: "3", name: "Oyi" },
    { id: "61", countryId: "4", name: "Abak" },
    { id: "62", countryId: "4", name: "Eastern Obolo" },
    { id: "63", countryId: "4", name: "Eket" },
    { id: "64", countryId: "4", name: "Esit-Eket" },
    { id: "65", countryId: "4", name: "Essien Udim" },
    { id: "66", countryId: "4", name: "Etim-Ekpo" },
    { id: "67", countryId: "4", name: "Etinan" },
    { id: "68", countryId: "4", name: "Ibeno" },
    { id: "69", countryId: "4", name: "Ibesikpo-Asutan" },
    { id: "70", countryId: "4", name: "Ibiono-Ibom" },
    { id: "71", countryId: "4", name: "Ika" },
    { id: "72", countryId: "4", name: "Ikono" },
    { id: "73", countryId: "4", name: "Ikot Abasi" },
    { id: "74", countryId: "4", name: "Ikot Ekpene" },
    { id: "75", countryId: "4", name: "Ini" },
    { id: "76", countryId: "4", name: "Itu" },
    { id: "77", countryId: "4", name: "Mbo" },
    { id: "78", countryId: "4", name: "Mkpat-Enin" },
    { id: "79", countryId: "4", name: "Nsit-Atai" },
    { id: "80", countryId: "4", name: "Nsit-Ibom" },
    { id: "81", countryId: "4", name: "Nsit-Ubium" },
    { id: "82", countryId: "4", name: "Obot-Akara" },
    { id: "83", countryId: "4", name: "Okobo" },
    { id: "84", countryId: "4", name: "Onna" },
    { id: "85", countryId: "4", name: "Oron" },
    { id: "86", countryId: "4", name: "Oruk Anam" },
    { id: "87", countryId: "4", name: "Udung Uko" },
    { id: "88", countryId: "4", name: "Ukanafun" },
    { id: "89", countryId: "4", name: "Uruan" },
    { id: "90", countryId: "4", name: "Urue-Offong/Oruko" },
    { id: "91", countryId: "4", name: "Uyo" },
    { id: "92", countryId: "5", name: "Alkaleri" },
    { id: "93", countryId: "5", name: "Bauchi" },
    { id: "94", countryId: "5", name: "Bauchi Town" },
    { id: "95", countryId: "5", name: "Bogoro" },
    { id: "96", countryId: "5", name: "Dambam" },
    { id: "97", countryId: "5", name: "Darazo" },
    { id: "98", countryId: "5", name: "Dass" },
    { id: "99", countryId: "5", name: "Gamawa" },
    { id: "100", countryId: "5", name: "Ganjuwa" },
    { id: "101", countryId: "5", name: "Giade" },
    { id: "102", countryId: "5", name: "Itas/Gadau" },
    { id: "103", countryId: "5", name: "Jama'are" },
    { id: "104", countryId: "5", name: "Katagum" },
    { id: "105", countryId: "5", name: "Kirfi" },
    { id: "106", countryId: "5", name: "Misau" },
    { id: "107", countryId: "5", name: "Ningi" },
    { id: "108", countryId: "5", name: "Shira" },
    { id: "109", countryId: "5", name: "Tafawa-Balewa" },
    { id: "110", countryId: "5", name: "Toro" },
    { id: "111", countryId: "5", name: "Warji" },
    { id: "112", countryId: "5", name: "Zaki" },
    { id: "113", countryId: "6", name: "Brass" },
    { id: "114", countryId: "6", name: "Ekeremor" },
    { id: "115", countryId: "6", name: "Kolokuma/Opokuma" },
    { id: "116", countryId: "6", name: "Nembe" },
    { id: "117", countryId: "6", name: "Ogbia" },
    { id: "118", countryId: "6", name: "Sagbama" },
    { id: "119", countryId: "6", name: "Southern Ijaw" },
    { id: "120", countryId: "6", name: "Yenagoa" },
    { id: "121", countryId: "7", name: "Ado" },
    { id: "122", countryId: "7", name: "Agatu" },
    { id: "123", countryId: "7", name: "Apa" },
    { id: "124", countryId: "7", name: "buruku" },
    { id: "125", countryId: "7", name: "Gboko" },
    { id: "126", countryId: "7", name: "Guma" },
    { id: "127", countryId: "7", name: "Gwer East" },
    { id: "128", countryId: "7", name: "Gwer West" },
    { id: "129", countryId: "7", name: "Katsina-Ala" },
    { id: "130", countryId: "7", name: "Konshisha" },
    { id: "131", countryId: "7", name: "Kwande" },
    { id: "132", countryId: "7", name: "Logo" },
    { id: "133", countryId: "7", name: "Makurdi" },
    { id: "134", countryId: "7", name: "Obi" },
    { id: "135", countryId: "7", name: "Ogbadibo" },
    { id: "136", countryId: "7", name: "Oju" },
    { id: "137", countryId: "7", name: "Okpokwu" },
    { id: "138", countryId: "7", name: "Ohimini" },
    { id: "139", countryId: "7", name: "Oturkpo" },
    { id: "140", countryId: "7", name: "Tarka" },
    { id: "141", countryId: "7", name: "Ukum" },
    { id: "142", countryId: "7", name: "Ushongo" },
    { id: "143", countryId: "7", name: "Vandeikya" },
    { id: "144", countryId: "8", name: "Abadam" },
    { id: "145", countryId: "8", name: "Askira/Uba" },
    { id: "146", countryId: "8", name: "Bama" },
    { id: "147", countryId: "8", name: "Bayo" },
    { id: "148", countryId: "8", name: "Biu" },
    { id: "149", countryId: "8", name: "Chibok" },
    { id: "150", countryId: "8", name: "Damboa" },
    { id: "151", countryId: "8", name: "Dikwa" },
    { id: "152", countryId: "8", name: "Gubio" },
    { id: "153", countryId: "8", name: "Guzamala" },
    { id: "154", countryId: "8", name: "Gwoza" },
    { id: "155", countryId: "8", name: "Hawul" },
    { id: "156", countryId: "8", name: "Jere" },
    { id: "157", countryId: "8", name: "Kaga" },
    { id: "158", countryId: "8", name: "Kala/Balge" },
    { id: "159", countryId: "8", name: "Konduga" },
    { id: "160", countryId: "8", name: "Kukawa" },
    { id: "161", countryId: "8", name: "Kwaya Kusar" },
    { id: "162", countryId: "8", name: "Mafa" },
    { id: "163", countryId: "8", name: "Magumeri" },
    { id: "164", countryId: "8", name: "Maiduguri" },
    { id: "165", countryId: "8", name: "Marte" },
    { id: "166", countryId: "8", name: "Mobbar" },
    { id: "167", countryId: "8", name: "Monguno" },
    { id: "168", countryId: "8", name: "Ngala" },
    { id: "169", countryId: "8", name: "Nganzai" },
    { id: "170", countryId: "8", name: "Shani" },
    { id: "171", countryId: "9", name: "Akpabuyo" },
    { id: "172", countryId: "9", name: "Odukpani" },
    { id: "173", countryId: "9", name: "Akamkpa" },
    { id: "174", countryId: "9", name: "Biase" },
    { id: "175", countryId: "9", name: "Abi" },
    { id: "176", countryId: "9", name: "Ikom" },
    { id: "177", countryId: "9", name: "Yarkur" },
    { id: "178", countryId: "9", name: "Odubra" },
    { id: "179", countryId: "9", name: "Boki" },
    { id: "180", countryId: "9", name: "Ogoja" },
    { id: "181", countryId: "9", name: "Yala" },
    { id: "182", countryId: "9", name: "Obanliku" },
    { id: "183", countryId: "9", name: "Obudu" },
    { id: "184", countryId: "9", name: "Calabar South" },
    { id: "185", countryId: "9", name: "Etung" },
    { id: "186", countryId: "9", name: "Bekwara" },
    { id: "187", countryId: "9", name: "Bakassi" },
    { id: "188", countryId: "9", name: "Calabar Municipality" },
    { id: "189", countryId: "10", name: "Oshimili" },
    { id: "190", countryId: "10", name: "Aniocha" },
    { id: "191", countryId: "10", name: "Aniocha South" },
    { id: "192", countryId: "10", name: "Ika South" },
    { id: "193", countryId: "10", name: "Ika North-East" },
    { id: "194", countryId: "10", name: "Ndokwa West" },
    { id: "195", countryId: "10", name: "Ndokwa East" },
    { id: "196", countryId: "10", name: "Isoko South" },
    { id: "197", countryId: "10", name: "Isoko North" },
    { id: "198", countryId: "10", name: "Bomadi" },
    { id: "199", countryId: "10", name: "Burutu" },
    { id: "200", countryId: "10", name: "Ughelli South" },
    { id: "201", countryId: "10", name: "Ughelli North" },
    { id: "202", countryId: "10", name: "Ethiope West" },
    { id: "203", countryId: "10", name: "Ethiope East" },
    { id: "204", countryId: "10", name: "Sapele" },
    { id: "205", countryId: "10", name: "Okpe" },
    { id: "206", countryId: "10", name: "Warri Central" },
    { id: "207", countryId: "10", name: "Warri North" },
    { id: "208", countryId: "10", name: "Warri South" },
    { id: "209", countryId: "10", name: "Udu" },
    { id: "210", countryId: "10", name: "Ukwani" },
    { id: "211", countryId: "10", name: "Uvwie" },
    { id: "212", countryId: "10", name: "Oshimili North" },
    { id: "213", countryId: "10", name: "Patani" },
    { id: "214", countryId: "11", name: "Edda" },
    { id: "215", countryId: "11", name: "Afikpo" },
    { id: "216", countryId: "11", name: "Onicha" },
    { id: "217", countryId: "11", name: "Ohaozara" },
    { id: "218", countryId: "11", name: "Abakaliki" },
    { id: "219", countryId: "11", name: "Ishielu" },
    { id: "220", countryId: "11", name: "Ikwo" },
    { id: "221", countryId: "11", name: "Ezza" },
    { id: "222", countryId: "11", name: "Ezza South" },
    { id: "221", countryId: "11", name: "Ohaukwu" },
    { id: "223", countryId: "11", name: "Ebonyi" },
    { id: "224", countryId: "11", name: "Ivo" },
    { id: "226", countryId: "12", name: "Enugu South" },
    { id: "227", countryId: "12", name: "Igbo-Eze South" },
    { id: "225", countryId: "12", name: "Enugu North" },
    { id: "228", countryId: "12", name: "Nkanu" },
    { id: "229", countryId: "12", name: "Udi-Agwu" },
    { id: "230", countryId: "12", name: "Oji River" },
    { id: "231", countryId: "12", name: "Ezeagu" },
    { id: "232", countryId: "12", name: "Igbo-Eze North" },
    { id: "233", countryId: "12", name: "Isi-Uzo" },
    { id: "234", countryId: "12", name: "Nsukka" },
    { id: "235", countryId: "12", name: "Igbo-Ekiti" },
    { id: "236", countryId: "12", name: "Uzo-Uwani" },
    { id: "237", countryId: "12", name: "Enugu East" },
    { id: "238", countryId: "12", name: "Aninri" },
    { id: "239", countryId: "12", name: "Nkanu East" },
    { id: "240", countryId: "12", name: "Udenu" },
    { id: "241", countryId: "13", name: "Esan North-East" },
    { id: "242", countryId: "13", name: "Esan Central" },
    { id: "243", countryId: "13", name: "Esan West" },
    { id: "244", countryId: "13", name: "Esan South-East" },
    { id: "245", countryId: "13", name: "Etsako Central" },
    { id: "246", countryId: "13", name: "Etsako East" },
    { id: "247", countryId: "13", name: "Egor" },
    { id: "248", countryId: "13", name: "Ukpoba" },
    { id: "249", countryId: "13", name: "Central" },
    { id: "250", countryId: "13", name: "Igueben" },
    { id: "251", countryId: "13", name: "Oredo" },
    { id: "252", countryId: "13", name: "Ovia South-West" },
    { id: "253", countryId: "13", name: "Ovia South-East" },
    { id: "254", countryId: "13", name: "Orhionwon" },
    { id: "255", countryId: "13", name: "Uhunmwonde" },
    { id: "256", countryId: "14", name: "Ado" },
    { id: "257", countryId: "14", name: "Ekiti East" },
    { id: "258", countryId: "14", name: "Ekiti West" },
    { id: "259", countryId: "14", name: "Ekiti South-West" },
    { id: "260", countryId: "14", name: "Emure/Ise/Orun" },
    { id: "261", countryId: "14", name: "Ikere" },
    { id: "262", countryId: "14", name: "Irepodun" },
    { id: "263", countryId: "14", name: "Ijero" },
    { id: "264", countryId: "14", name: "Ido/Osi" },
    { id: "265", countryId: "14", name: "Oye" },
    { id: "266", countryId: "14", name: "Ikole" },
    { id: "267", countryId: "14", name: "Moba" },
    { id: "268", countryId: "14", name: "Gbonyin" },
    { id: "269", countryId: "14", name: "Efon" },
    { id: "270", countryId: "14", name: "Ise/Orun" },
    { id: "271", countryId: "14", name: "Ilejemeje" },
    { id: "272", countryId: "15", name: "Abaji" },
    { id: "273", countryId: "15", name: "Abuja Municipal" },
    { id: "274", countryId: "15", name: "Bwari" },
    { id: "275", countryId: "15", name: "Gwagwalada" },
    { id: "276", countryId: "15", name: "Kuje" },
    { id: "277", countryId: "15", name: "Kwali" },
    { id: "278", countryId: "16", name: "Akko" },
    { id: "279", countryId: "16", name: "Balanga" },
    { id: "280", countryId: "16", name: "Billiri" },
    { id: "281", countryId: "16", name: "Dukku" },
    { id: "282", countryId: "16", name: "Kaltungo" },
    { id: "283", countryId: "16", name: "Kwami" },
    { id: "284", countryId: "16", name: "Shomgom" },
    { id: "285", countryId: "16", name: "Funakaye" },
    { id: "286", countryId: "16", name: "Gombe" },
    { id: "287", countryId: "16", name: "Nafada/Bajoga" },
    { id: "288", countryId: "16", name: "Yamaltu/Delta" },
    { id: "289", countryId: "17", name: "Aboh-Mbaise" },
    { id: "290", countryId: "17", name: "Ahiazu-Mbaise" },
    { id: "291", countryId: "17", name: "Ehime-Mbano" },
    { id: "292", countryId: "17", name: "Ezinihitte" },
    { id: "293", countryId: "17", name: "Ideato North" },
    { id: "294", countryId: "17", name: "Ideato South" },
    { id: "295", countryId: "17", name: "Ihitte/Uboma" },
    { id: "296", countryId: "17", name: "Ikeduru" },
    { id: "297", countryId: "17", name: "Isiala Mbano" },
    { id: "298", countryId: "17", name: "Isu" },
    { id: "299", countryId: "17", name: "Mbaitoli" },
    { id: "300", countryId: "17", name: "Ngor-Okpala" },
    { id: "301", countryId: "17", name: "Njaba" },
    { id: "302", countryId: "17", name: "Nwangele" },
    { id: "303", countryId: "17", name: "Nkwerre" },
    { id: "304", countryId: "17", name: "Obowo" },
    { id: "305", countryId: "17", name: "Oguta" },
    { id: "306", countryId: "17", name: "Ohaji/Egbema" },
    { id: "307", countryId: "17", name: "Okigwe" },
    { id: "308", countryId: "17", name: "Orlu" },
    { id: "309", countryId: "17", name: "Orsu" },
    { id: "310", countryId: "17", name: "Oru East" },
    { id: "311", countryId: "17", name: "Oru West" },
    { id: "312", countryId: "17", name: "Owerri Municipal" },
    { id: "313", countryId: "17", name: "Owerri North" },
    { id: "314", countryId: "17", name: "Owerri West" },
    { id: "315", countryId: "18", name: "Auyo" },
    { id: "316", countryId: "18", name: "Babura" },
    { id: "317", countryId: "18", name: "Birni Kudu" },
    { id: "318", countryId: "18", name: "Birniwa" },
    { id: "319", countryId: "18", name: "Buji" },
    { id: "320", countryId: "18", name: "Dutse" },
    { id: "321", countryId: "18", name: "Gagarawa" },
    { id: "322", countryId: "18", name: "Garki" },
    { id: "323", countryId: "18", name: "Gumel" },
    { id: "324", countryId: "18", name: "Guri" },
    { id: "325", countryId: "18", name: "Gwaram" },
    { id: "326", countryId: "18", name: "Gwiwa" },
    { id: "327", countryId: "18", name: "Hadejia" },
    { id: "328", countryId: "18", name: "Jahun" },
    { id: "329", countryId: "18", name: "Kafin Hausa" },
    { id: "330", countryId: "18", name: "Kaugama Kazaure" },
    { id: "331", countryId: "18", name: "Kiri Kasamma" },
    { id: "332", countryId: "18", name: "Kiyawa" },
    { id: "333", countryId: "18", name: "Maigatari" },
    { id: "334", countryId: "18", name: "Malam Madori" },
    { id: "335", countryId: "18", name: "Miga" },
    { id: "336", countryId: "18", name: "Ringim" },
    { id: "337", countryId: "18", name: "Roni" },
    { id: "338", countryId: "18", name: "Sule-Tankarkar" },
    { id: "339", countryId: "18", name: "Taura" },
    { id: "340", countryId: "18", name: "Yankwashi" },
    { id: "341", countryId: "19", name: "Birni-Gwari" },
    { id: "342", countryId: "19", name: "Chikun" },
    { id: "343", countryId: "19", name: "Giwa" },
    { id: "344", countryId: "19", name: "Igabi" },
    { id: "345", countryId: "19", name: "Ikara" },
    { id: "346", countryId: "19", name: "Jaba" },
    { id: "347", countryId: "19", name: "Jema'a" },
    { id: "348", countryId: "19", name: "Kachia" },
    { id: "349", countryId: "19", name: "Kaduna North" },
    { id: "350", countryId: "19", name: "Kaduna South" },
    { id: "351", countryId: "19", name: "Kagarko" },
    { id: "352", countryId: "19", name: "Kajuru" },
    { id: "353", countryId: "19", name: "Kaura" },
    { id: "354", countryId: "19", name: "Kauru" },
    { id: "355", countryId: "19", name: "Kubau" },
    { id: "356", countryId: "19", name: "Kudan" },
    { id: "357", countryId: "19", name: "Lere" },
    { id: "358", countryId: "19", name: "Makarfi" },
    { id: "359", countryId: "19", name: "Sabon-Gari" },
    { id: "360", countryId: "19", name: "Sanga" },
    { id: "361", countryId: "19", name: "Soba" },
    { id: "362", countryId: "19", name: "Zango-Kataf" },
    { id: "363", countryId: "19", name: "Ajingi" },
    { id: "364", countryId: "20", name: "Albasu" },
    { id: "365", countryId: "20", name: "Bagwai" },
    { id: "366", countryId: "20", name: "Bebeji" },
    { id: "367", countryId: "20", name: "Bichi" },
    { id: "368", countryId: "20", name: "Bunkure" },
    { id: "369", countryId: "20", name: "Dala" },
    { id: "370", countryId: "20", name: "Dambatta" },
    { id: "371", countryId: "20", name: "Dawakin Kudu" },
    { id: "372", countryId: "20", name: "Dawakin Tofa" },
    { id: "373", countryId: "20", name: "Doguwa" },
    { id: "374", countryId: "20", name: "Fagge" },
    { id: "375", countryId: "20", name: "Gabasawa" },
    { id: "376", countryId: "20", name: "Garko" },
    { id: "377", countryId: "20", name: "Garum" },
    { id: "378", countryId: "20", name: "Mallam" },
    { id: "379", countryId: "20", name: "Gaya" },
    { id: "380", countryId: "20", name: "Gezawa" },
    { id: "381", countryId: "20", name: "Gwale" },
    { id: "382", countryId: "20", name: "Gwarzo" },
    { id: "383", countryId: "20", name: "Kabo" },
    { id: "384", countryId: "20", name: "Kano Municipal" },
    { id: "385", countryId: "20", name: "Karaye" },
    { id: "386", countryId: "20", name: "Kibiya" },
    { id: "387", countryId: "20", name: "Kiru" },
    { id: "388", countryId: "20", name: "Kumbotso" },
    { id: "389", countryId: "20", name: "Ghari" },
    { id: "390", countryId: "20", name: "Kura" },
    { id: "391", countryId: "20", name: "Madobi" },
    { id: "392", countryId: "20", name: "Makoda" },
    { id: "393", countryId: "20", name: "Minjibir" },
    { id: "394", countryId: "20", name: "Nasarawa" },
    { id: "395", countryId: "20", name: "Rano" },
    { id: "396", countryId: "20", name: "Rimin Gado" },
    { id: "397", countryId: "20", name: "Rogo" },
    { id: "398", countryId: "20", name: "Shanono" },
    { id: "399", countryId: "20", name: "Sumaila" },
    { id: "400", countryId: "20", name: "Takali" },
    { id: "401", countryId: "20", name: "Tarauni" },
    { id: "402", countryId: "20", name: "Tofa" },
    { id: "403", countryId: "20", name: "Tsanyawa" },
    { id: "404", countryId: "20", name: "Tudun Wada" },
    { id: "405", countryId: "20", name: "Ungogo" },
    { id: "406", countryId: "20", name: "Warawa" },
    { id: "407", countryId: "20", name: "Wudil" },
    { id: "408", countryId: "21", name: "Bakori" },
    { id: "409", countryId: "21", name: "Batagarawa" },
    { id: "410", countryId: "21", name: "Batsari" },
    { id: "411", countryId: "21", name: "Baure" },
    { id: "412", countryId: "21", name: "Bindawa" },
    { id: "413", countryId: "21", name: "Charanchi" },
    { id: "414", countryId: "21", name: "Dandume" },
    { id: "415", countryId: "21", name: "Danja" },
    { id: "416", countryId: "21", name: "Dan Musa" },
    { id: "417", countryId: "21", name: "Daura" },
    { id: "418", countryId: "21", name: "Dutsi" },
    { id: "419", countryId: "21", name: "Dutsin-Ma" },
    { id: "420", countryId: "21", name: "Faskari" },
    { id: "421", countryId: "21", name: "Funtua" },
    { id: "422", countryId: "21", name: "Ingawa" },
    { id: "423", countryId: "21", name: "Jibia" },
    { id: "424", countryId: "21", name: "Kafur" },
    { id: "425", countryId: "21", name: "Kaita" },
    { id: "426", countryId: "21", name: "Kankara" },
    { id: "427", countryId: "21", name: "Kankia" },
    { id: "428", countryId: "21", name: "Katsina" },
    { id: "429", countryId: "21", name: "Kurfi" },
    { id: "430", countryId: "21", name: "Kusada" },
    { id: "431", countryId: "21", name: "Mai'Adua" },
    { id: "432", countryId: "21", name: "Malumfashi" },
    { id: "433", countryId: "21", name: "Mani" },
    { id: "434", countryId: "21", name: "Mashi" },
    { id: "435", countryId: "21", name: "Matazuu" },
    { id: "436", countryId: "21", name: "Musawa" },
    { id: "437", countryId: "21", name: "Rimi" },
    { id: "438", countryId: "21", name: "Sabuwa" },
    { id: "439", countryId: "21", name: "Safana" },
    { id: "440", countryId: "21", name: "Sandamu" },
    { id: "441", countryId: "21", name: "Zango" },
    { id: "442", countryId: "22", name: "Aleiro" },
    { id: "443", countryId: "22", name: "Arewa-Dandi" },
    { id: "444", countryId: "22", name: "Argungu" },
    { id: "445", countryId: "22", name: "Augie" },
    { id: "446", countryId: "22", name: "Bagudo" },
    { id: "447", countryId: "22", name: "Birnin Kebbi" },
    { id: "448", countryId: "22", name: "Bunza" },
    { id: "449", countryId: "22", name: "Dandi" },
    { id: "450", countryId: "22", name: "Fakai" },
    { id: "451", countryId: "22", name: "Gwandu" },
    { id: "452", countryId: "22", name: "Jega" },
    { id: "453", countryId: "22", name: "Kalgo" },
    { id: "454", countryId: "22", name: "Koko/Besse" },
    { id: "455", countryId: "22", name: "Maiyama" },
    { id: "456", countryId: "22", name: "Ngaski" },
    { id: "457", countryId: "22", name: "Sakaba" },
    { id: "458", countryId: "22", name: "Shanga" },
    { id: "459", countryId: "22", name: "Suru" },
    { id: "460", countryId: "22", name: "Wasagu/Danko" },
    { id: "461", countryId: "22", name: "Yauri" },
    { id: "462", countryId: "22", name: "Zuru" },
    { id: "463", countryId: "23", name: "Adavi" },
    { id: "464", countryId: "23", name: "Ajaokuta" },
    { id: "465", countryId: "23", name: "Ankpa" },
    { id: "466", countryId: "23", name: "Bassa" },
    { id: "467", countryId: "23", name: "Dekina" },
    { id: "468", countryId: "23", name: "Ibaji" },
    { id: "469", countryId: "23", name: "Idah" },
    { id: "470", countryId: "23", name: "Igalamela-Odolu" },
    { id: "471", countryId: "23", name: "Ijumu" },
    { id: "472", countryId: "23", name: "Kabba/Bunu" },
    { id: "473", countryId: "23", name: "Kogi" },
    { id: "474", countryId: "23", name: "Lokoja" },
    { id: "475", countryId: "23", name: "Mopa-Muro" },
    { id: "476", countryId: "23", name: "Ofu" },
    { id: "477", countryId: "23", name: "Ogori/Mangongo" },
    { id: "478", countryId: "23", name: "Okehi" },
    { id: "479", countryId: "23", name: "Okene" },
    { id: "480", countryId: "23", name: "Olamabolo" },
    { id: "481", countryId: "23", name: "Omala" },
    { id: "482", countryId: "23", name: "Yagba East" },
    { id: "483", countryId: "23", name: "Yagba West" },
    { id: "484", countryId: "24", name: "Asa" },
    { id: "485", countryId: "24", name: "Baruten" },
    { id: "486", countryId: "24", name: "Edu" },
    { id: "487", countryId: "24", name: "Ekiti" },
    { id: "488", countryId: "24", name: "Ifelodun" },
    { id: "489", countryId: "24", name: "Ilorin East" },
    { id: "490", countryId: "24", name: "Ilorin West" },
    { id: "491", countryId: "24", name: "Irepodun" },
    { id: "492", countryId: "24", name: "Isin" },
    { id: "493", countryId: "24", name: "Kaiama" },
    { id: "494", countryId: "24", name: "Moro" },
    { id: "495", countryId: "24", name: "Offa" },
    { id: "496", countryId: "24", name: "Oke-Ero" },
    { id: "497", countryId: "24", name: "Oyun" },
    { id: "498", countryId: "24", name: "Pategi" },
    { id: "499", countryId: "25", name: "Agege LGA: Agege LCDA" },
    { id: "500", countryId: "25", name: "Agege LGA: Orile-Agege LCDA" },
    { id: "501", countryId: "25", name: "Ajeromi/Ifelodun LGA: Ajeromi LCDA" },
    { id: "502", countryId: "25", name: "Ajeromi/Ifelodun LGA: Ifelodun LCDA" },
    { id: "503", countryId: "25", name: "Alimosho LGA: Alimosho LCDA" },
    { id: "504", countryId: "25", name: "Alimosho LGA: Agbado/Oke-Odo LCDA" },
    { id: "505", countryId: "25", name: "Alimosho LGA: Ayobo-Ipaja LCDA" },
    { id: "506", countryId: "25", name: "Alimosho LGA: Egbe-Idimu LCDA" },
    { id: "507", countryId: "25", name: "Alimosho LGA: Igando-Ikotun LCDA" },
    { id: "508", countryId: "25", name: "Alimosho LGA: Mosan Okunola LCDA" },
    { id: "509", countryId: "25", name: "Amuwo-Odofin LGA: Amuwo-Odofin LCDA" },
    { id: "510", countryId: "25", name: "Amuwo-Odofin LGA: Oriade LCDA" },
    { id: "511", countryId: "25", name: "Apapa LGA: Apapa LCDA" },
    { id: "512", countryId: "25", name: "Apapa LGA: Apapa Iganmu LCDA" },
    { id: "513", countryId: "25", name: "Badagry LGA: Badagry LCDA" },
    { id: "514", countryId: "25", name: "Badagry LGA: Badagry West LCDA" },
    { id: "515", countryId: "25", name: "Badagry LGA: Olorunda LCDA" },
    { id: "516", countryId: "25", name: "Epe LGA: Epe LCDA" },
    { id: "517", countryId: "25", name: "Epe LGA: Eredo LCDA" },
    { id: "518", countryId: "25", name: "Epe LGA: Ikosi-Ejinrin LCDA" },
    { id: "519", countryId: "25", name: "Eti-Osa LGA: Eti-Osa East LCDA" },
    { id: "520", countryId: "25", name: "Eti-Osa LGA: Eti-Osa West LCDA" },
    {
      id: "521",
      countryId: "25",
      name: "Eti-Osa LGA: Iru-Victoria Island LCDA",
    },
    { id: "522", countryId: "25", name: "Eti-Osa LGA: Ikoyi-Obalende LCDA" },
    { id: "523", countryId: "25", name: "Ibeju-Lekki LGA: Ibeju LCDA" },
    { id: "524", countryId: "25", name: "Ibeju Lekki LGA: Lekki LCDA" },
    { id: "525", countryId: "25", name: "Ifako/Ijaiye LGA: Ifako/Ijaiye LCDA" },
    { id: "526", countryId: "25", name: "Ifako-Ijaiye LGA: Ojokoro LCDA" },
    { id: "527", countryId: "25", name: "Ikeja LGA: Ikeja LCDA" },
    { id: "528", countryId: "25", name: "Ikeja LGA: Ojodu LCDA" },
    { id: "529", countryId: "25", name: "Ikeja LGA: Onigbongbo" },
    { id: "530", countryId: "25", name: "Ikorodu LGA: Ikorodu LCDA" },
    { id: "531", countryId: "25", name: "Ikorodu LGA: Ikorodu North LCDA" },
    { id: "532", countryId: "25", name: "Ikorodu LGA: Ikorodu West LCDA" },
    { id: "533", countryId: "25", name: "Ikorodu LGA: Imota LCDA" },
    { id: "534", countryId: "25", name: "Ikorodu LGA: Ijede LCDA" },
    { id: "535", countryId: "25", name: "Ikorodu LGA: Igbogbo-Baiyeku LCDA" },
    { id: "536", countryId: "25", name: "Kosofe LGA: Kosofe LCDA" },
    { id: "537", countryId: "25", name: "Kosofe LGA: Ikosi-Isheri LCDA" },
    { id: "538", countryId: "25", name: "Kosofe LGA: Agboyi-Ketu LCDA" },
    {
      id: "539",
      countryId: "25",
      name: "Lagos Island LGA: Lagos Island East LCDA",
    },
    {
      id: "540",
      countryId: "25",
      name: "Lagos Island LGA: Lagos Island West LCDA",
    },
    {
      id: "541",
      countryId: "25",
      name: "Lagos Mainland LGA: Lagos Mainland LCDA",
    },
    { id: "542", countryId: "25", name: "Lagos Mainland LGA: Yaba LCDA" },
    { id: "543", countryId: "25", name: "Mushin LGA: Mushin LCDA" },
    { id: "544", countryId: "25", name: "Mushin LGA: Odi-Olowo LCDA" },
    { id: "545", countryId: "25", name: "Ojo LGA: Ojo LCDA" },
    { id: "546", countryId: "25", name: "Ojo LGA: Oto-Awori LCDA" },
    { id: "547", countryId: "25", name: "Ojo LGA: Iba LCDA" },
    { id: "548", countryId: "25", name: "Shomolu LGA: Shomolu LCDA" },
    { id: "549", countryId: "25", name: "Shomolu LGA: Bariga LCDA" },
    { id: "550", countryId: "25", name: "Oshodi/Isolo LGA: Ejigbo LCDA" },
    { id: "551", countryId: "25", name: "Oshodi/Isolo LGA: Isolo LCDA" },
    { id: "552", countryId: "25", name: "Oshodi/Isolo LGA: Oshodi LCDA" },
    { id: "553", countryId: "25", name: "Surulere LGA: Surulere LCDA" },
    { id: "554", countryId: "25", name: "Surulere LGA: Coker Aguda LCDA" },
    { id: "555", countryId: "25", name: "Surulere LGA: Itire-Ikate LCDA" },
    { id: "556", countryId: "26", name: "Akwanga" },
    { id: "557", countryId: "26", name: "Awe" },
    { id: "558", countryId: "26", name: "Doma" },
    { id: "559", countryId: "26", name: "Karu" },
    { id: "560", countryId: "26", name: "Keana" },
    { id: "561", countryId: "26", name: "Keffi" },
    { id: "562", countryId: "26", name: "Kokona" },
    { id: "563", countryId: "26", name: "Lafia" },
    { id: "564", countryId: "26", name: "Nasarawa" },
    { id: "565", countryId: "26", name: "Nasarawa-Eggon" },
    { id: "566", countryId: "26", name: "Obi" },
    { id: "567", countryId: "26", name: "Toto" },
    { id: "568", countryId: "26", name: "Wambe" },
    { id: "569", countryId: "27", name: "Agaie" },
    { id: "570", countryId: "27", name: "Agwara" },
    { id: "571", countryId: "27", name: "Bida" },
    { id: "572", countryId: "27", name: "Borgu" },
    { id: "573", countryId: "27", name: "Bosso" },
    { id: "574", countryId: "27", name: "Chanchaga" },
    { id: "575", countryId: "27", name: "Edati" },
    { id: "576", countryId: "27", name: "Gbako" },
    { id: "577", countryId: "27", name: "Gurara" },
    { id: "578", countryId: "27", name: "Tafa" },
    { id: "579", countryId: "27", name: "Katcha" },
    { id: "580", countryId: "27", name: "Kontagora" },
    { id: "581", countryId: "27", name: "Lapai" },
    { id: "582", countryId: "27", name: "Lavun" },
    { id: "583", countryId: "27", name: "Magama" },
    { id: "584", countryId: "27", name: "Mariga" },
    { id: "585", countryId: "27", name: "Mashegu" },
    { id: "586", countryId: "27", name: "Mokwa" },
    { id: "587", countryId: "27", name: "Muya" },
    { id: "588", countryId: "27", name: "Pailoro" },
    { id: "589", countryId: "27", name: "Rafi" },
    { id: "590", countryId: "27", name: "Rijau" },
    { id: "591", countryId: "27", name: "Shiroro" },
    { id: "592", countryId: "27", name: "Suleja" },
    { id: "593", countryId: "27", name: "Wushishi" },
    { id: "594", countryId: "28", name: "Abeokuta North" },
    { id: "595", countryId: "28", name: "Abeokuta South" },
    { id: "596", countryId: "28", name: "Ado-Odo/Ota" },
    { id: "597", countryId: "28", name: "Yewa North" },
    { id: "598", countryId: "28", name: "Yewa South" },
    { id: "599", countryId: "28", name: "Ewekoro" },
    { id: "600", countryId: "28", name: "Ifo" },
    { id: "601", countryId: "28", name: "Ijebu East" },
    { id: "602", countryId: "28", name: "Ijebu North" },
    { id: "603", countryId: "28", name: "Ijebu North East" },
    { id: "604", countryId: "28", name: "Ijebu Ode" },
    { id: "605", countryId: "28", name: "Ikenne" },
    { id: "606", countryId: "28", name: "Imeko-Afon" },
    { id: "607", countryId: "28", name: "Ipokia" },
    { id: "608", countryId: "28", name: "Obafemi-Owode" },
    { id: "609", countryId: "28", name: "Ogun Waterside" },
    { id: "610", countryId: "28", name: "Odeda" },
    { id: "611", countryId: "28", name: "Odogbolu" },
    { id: "612", countryId: "28", name: "Remo North" },
    { id: "613", countryId: "28", name: "Shagamu" },
    { id: "614", countryId: "29", name: "Akoko North-East" },
    { id: "615", countryId: "29", name: "Akoko North-West" },
    { id: "616", countryId: "29", name: "Akoko South" },
    { id: "617", countryId: "29", name: "Akoko South-West" },
    { id: "618", countryId: "29", name: "Akure East" },
    { id: "619", countryId: "29", name: "Akure North" },
    { id: "620", countryId: "29", name: "Akure South" },
    { id: "621", countryId: "29", name: "Ese-Odo" },
    { id: "622", countryId: "29", name: "Idanre" },
    { id: "623", countryId: "29", name: "Ifedore" },
    { id: "624", countryId: "29", name: "Ilaje" },
    { id: "625", countryId: "29", name: "Ile-Oluji" },
    { id: "626", countryId: "29", name: "Okeigbo" },
    { id: "627", countryId: "29", name: "Irele" },
    { id: "628", countryId: "29", name: "Okitipupa" },
    { id: "629", countryId: "29", name: "Ondo East" },
    { id: "630", countryId: "29", name: "Ondo West" },
    { id: "631", countryId: "29", name: "Odigbo" },
    { id: "632", countryId: "29", name: "Ose" },
    { id: "633", countryId: "29", name: "Owo" },
    { id: "634", countryId: "30", name: "Aiyedade" },
    { id: "635", countryId: "30", name: "Aiyedire" },
    { id: "636", countryId: "30", name: "Atakumosa East" },
    { id: "637", countryId: "30", name: "Atakumosa West" },
    { id: "638", countryId: "30", name: "Boluwaduro" },
    { id: "639", countryId: "30", name: "Boripe" },
    { id: "640", countryId: "30", name: "Ede North" },
    { id: "641", countryId: "30", name: "Ede South" },
    { id: "642", countryId: "30", name: "Egbedore" },
    { id: "643", countryId: "30", name: "Ejigbo" },
    { id: "644", countryId: "30", name: "Ife Central" },
    { id: "645", countryId: "30", name: "Ife East" },
    { id: "646", countryId: "30", name: "Ife North" },
    { id: "647", countryId: "30", name: "Ife South" },
    { id: "648", countryId: "30", name: "Ifedayo" },
    { id: "649", countryId: "30", name: "Ifelodun" },
    { id: "650", countryId: "30", name: "Ila" },
    { id: "651", countryId: "30", name: "Ilesha East" },
    { id: "652", countryId: "30", name: "Ilesha West" },
    { id: "653", countryId: "30", name: "Irepodun" },
    { id: "654", countryId: "30", name: "Irewole" },
    { id: "655", countryId: "30", name: "Isokan" },
    { id: "656", countryId: "30", name: "Iwo" },
    { id: "657", countryId: "30", name: "Obokun" },
    { id: "658", countryId: "30", name: "Odo-Otin" },
    { id: "659", countryId: "30", name: "Ola-Oluwa" },
    { id: "660", countryId: "30", name: "Olorunda" },
    { id: "661", countryId: "30", name: "Oriade" },
    { id: "662", countryId: "30", name: "Orolu" },
    { id: "663", countryId: "30", name: "Osogbo" },
    { id: "664", countryId: "31", name: "Afijio" },
    { id: "665", countryId: "31", name: "Akinyele" },
    { id: "666", countryId: "31", name: "Ibadan Central" },
    { id: "667", countryId: "31", name: "Ibadan North" },
    { id: "668", countryId: "31", name: "Ibadan North-West" },
    { id: "669", countryId: "31", name: "Ibadan South-East" },
    { id: "670", countryId: "31", name: "Ibadan South-West" },
    { id: "671", countryId: "31", name: "Ibarapa Central" },
    { id: "672", countryId: "31", name: "Ibarapa East" },
    { id: "673", countryId: "31", name: "Ibarapa North" },
    { id: "674", countryId: "31", name: "Ido" },
    { id: "675", countryId: "31", name: "Irepo" },
    { id: "676", countryId: "31", name: "Iseyin" },
    { id: "677", countryId: "31", name: "Itesiwaju" },
    { id: "678", countryId: "31", name: "Iwajowa" },
    { id: "679", countryId: "31", name: "Kajola" },
    { id: "680", countryId: "31", name: "Lagelu Ogbomosho North" },
    { id: "681", countryId: "31", name: "Ogbomosho South" },
    { id: "682", countryId: "31", name: "Ogo Oluwa" },
    { id: "683", countryId: "31", name: "Olorunsogo" },
    { id: "684", countryId: "31", name: "Oluyole" },
    { id: "685", countryId: "31", name: "Ona-Ara" },
    { id: "686", countryId: "31", name: "Orelope" },
    { id: "687", countryId: "31", name: "Ori Ire" },
    { id: "688", countryId: "31", name: "Oyo East" },
    { id: "689", countryId: "31", name: "Oyo West" },
    { id: "690", countryId: "31", name: "Saki East" },
    { id: "691", countryId: "31", name: "Saki West" },
    { id: "692", countryId: "31", name: "Surulere" },
    { id: "693", countryId: "31", name: "Atiba" },
    { id: "694", countryId: "31", name: "Atisibo" },
    { id: "695", countryId: "31", name: "Egbeda" },
    { id: "696", countryId: "32", name: "Barikin Ladi" },
    { id: "697", countryId: "32", name: "Bassa" },
    { id: "698", countryId: "32", name: "Bokkos" },
    { id: "699", countryId: "32", name: "Jos East" },
    { id: "700", countryId: "32", name: "Jos North" },
    { id: "701", countryId: "32", name: "Jos South" },
    { id: "702", countryId: "32", name: "Kanam" },
    { id: "703", countryId: "32", name: "Kanke" },
    { id: "704", countryId: "32", name: "Langtang North" },
    { id: "705", countryId: "32", name: "Langtang South" },
    { id: "706", countryId: "32", name: "Mangu" },
    { id: "707", countryId: "32", name: "Mikang" },
    { id: "708", countryId: "32", name: "Pankshin" },
    { id: "709", countryId: "32", name: "Qua'an Pan" },
    { id: "710", countryId: "32", name: "Riyom" },
    { id: "711", countryId: "32", name: "Shendam" },
    { id: "712", countryId: "32", name: "Wase" },
    { id: "713", countryId: "33", name: "Abua/Odual" },
    { id: "714", countryId: "33", name: "Ahoada East" },
    { id: "715", countryId: "33", name: "Ahoada West" },
    { id: "716", countryId: "33", name: "Akuku Toru" },
    { id: "717", countryId: "33", name: "Andoni" },
    { id: "718", countryId: "33", name: "Asari-Toru" },
    { id: "719", countryId: "33", name: "Bonny" },
    { id: "720", countryId: "33", name: "Degema" },
    { id: "721", countryId: "33", name: "Emohua" },
    { id: "722", countryId: "33", name: "Eleme" },
    { id: "723", countryId: "33", name: "Etche" },
    { id: "724", countryId: "33", name: "Gokana" },
    { id: "725", countryId: "33", name: "Ikwerre" },
    { id: "726", countryId: "33", name: "Khana" },
    { id: "727", countryId: "33", name: "Obio/Akpor" },
    { id: "728", countryId: "33", name: "Ogba/Egbema/Ndoni" },
    { id: "729", countryId: "33", name: "Ogu/Bolo" },
    { id: "730", countryId: "33", name: "Okrika" },
    { id: "731", countryId: "33", name: "Omumma" },
    { id: "732", countryId: "33", name: "Opobo/Nkoro" },
    { id: "733", countryId: "33", name: "Oyigbo" },
    { id: "734", countryId: "33", name: "Port-Harcourt" },
    { id: "735", countryId: "33", name: "Tai" },
    { id: "736", countryId: "34", name: "Binji" },
    { id: "737", countryId: "34", name: "Bodinga" },
    { id: "738", countryId: "34", name: "Dange-Shinsi" },
    { id: "739", countryId: "34", name: "Gada" },
    { id: "740", countryId: "34", name: "Goronyo" },
    { id: "741", countryId: "34", name: "Gudu" },
    { id: "742", countryId: "34", name: "Gawabawa" },
    { id: "743", countryId: "34", name: "Illela" },
    { id: "744", countryId: "34", name: "Isa" },
    { id: "745", countryId: "34", name: "Kware" },
    { id: "746", countryId: "34", name: "Kebbe" },
    { id: "747", countryId: "34", name: "Rabah" },
    { id: "748", countryId: "34", name: "Sabon Birni" },
    { id: "749", countryId: "34", name: "Shagari" },
    { id: "750", countryId: "34", name: "Silame" },
    { id: "751", countryId: "34", name: "Sokoto North" },
    { id: "752", countryId: "34", name: "Sokoto South" },
    { id: "753", countryId: "34", name: "Tambuwal" },
    { id: "754", countryId: "34", name: "Tangaza" },
    { id: "755", countryId: "34", name: "Tureta" },
    { id: "756", countryId: "34", name: "Wamako" },
    { id: "757", countryId: "34", name: "Wurno" },
    { id: "758", countryId: "34", name: "Yabo" },
    { id: "759", countryId: "35", name: "Ardo-Kola" },
    { id: "760", countryId: "35", name: "Bali" },
    { id: "761", countryId: "35", name: "Donga" },
    { id: "762", countryId: "35", name: "Gashaka" },
    { id: "763", countryId: "35", name: "Cassol" },
    { id: "764", countryId: "35", name: "Ibi" },
    { id: "765", countryId: "35", name: "Jalingo" },
    { id: "766", countryId: "35", name: "Karin-Lamido" },
    { id: "767", countryId: "35", name: "Kurmi" },
    { id: "768", countryId: "35", name: "Lau" },
    { id: "769", countryId: "35", name: "Sardauna" },
    { id: "770", countryId: "35", name: "Takum" },
    { id: "771", countryId: "35", name: "Ussa" },
    { id: "772", countryId: "35", name: "Wukari" },
    { id: "773", countryId: "35", name: "Yorro" },
    { id: "774", countryId: "35", name: "Zing" },
    { id: "775", countryId: "36", name: "Bade" },
    { id: "776", countryId: "36", name: "Bursari" },
    { id: "777", countryId: "36", name: "Damaturu" },
    { id: "778", countryId: "36", name: "Fika" },
    { id: "779", countryId: "36", name: "Fune" },
    { id: "780", countryId: "36", name: "Geidam" },
    { id: "781", countryId: "36", name: "Gujba" },
    { id: "782", countryId: "36", name: "Gulani" },
    { id: "783", countryId: "36", name: "Jakusko" },
    { id: "784", countryId: "36", name: "Karasuwa" },
    { id: "785", countryId: "36", name: "Karawa" },
    { id: "786", countryId: "36", name: "Machina" },
    { id: "787", countryId: "36", name: "Nangere" },
    { id: "788", countryId: "36", name: "Nguru Potiskum" },
    { id: "789", countryId: "36", name: "Tarmua" },
    { id: "790", countryId: "36", name: "Yunusari" },
    { id: "791", countryId: "36", name: "Yusufari" },
    { id: "792", countryId: "37", name: "Anka" },
    { id: "793", countryId: "37", name: "Bakura" },
    { id: "794", countryId: "37", name: "Birnin Magaji" },
    { id: "795", countryId: "37", name: "Bukkuyum" },
    { id: "796", countryId: "37", name: "Bungudu" },
    { id: "797", countryId: "37", name: "Gummi" },
    { id: "798", countryId: "37", name: "Gusau" },
    { id: "799", countryId: "37", name: "Kaura" },
    { id: "800", countryId: "37", name: "Namoda" },
    { id: "801", countryId: "37", name: "Maradun" },
    { id: "802", countryId: "37", name: "Maru" },
    { id: "803", countryId: "37", name: "Shinkafi" },
    { id: "804", countryId: "37", name: "Talata Mafara" },
    { id: "805", countryId: "37", name: "Tsafe" },
    { id: "806", countryId: "37", name: "Zurmi" },
  ];
  const [country, setCountry] = useState([]);
  const [state, setState] = useState([]);

  useEffect(() => {
    setCountry(countries);
  }, []);

  const handleCountry = (id) => {
    const dt = states.filter((x) => x.countryId === id);
    setState(dt);
  };

  return (
    <div className="dropDown">
      <select
        id="ddlCountry"
        className="formControl selectClass"
        onChange={(e) => handleCountry(e.target.value)}
      >
        <option value="0">Select State</option>
        {country && country !== undefined
          ? country.map((ctr, index) => {
              return (
                <option key={index} value={ctr.id}>
                  {ctr.name}
                </option>
              );
            })
          : "No State"}
      </select>

      <select
        id="ddlStates"
        className="formControl selectClass"
        
      >
        <option value="0">Select LGA</option>
        {state && state !== undefined
          ? state.map((ctr, index) => {
              return (
                <option key={index} value={ctr.id}>
                  {ctr.name}
                </option>
              );
            })
          : "No LGA"}
      </select>

      <div id="inputBlock"></div>
    </div>
  );
}

export default Location;
